### ISSUE TITLE
Pull fixes from moby/storage

### ISSUE THREAD

**Issue by redbaron** [containers/storage#104]
Sorry if I misunderstand intention of this project, looks like it is aiming to implement docker features in a docker-independent way, yet it reuses a lot of docker code.

There were few fixes done do docker graphdrivers year ago, which I can find in a current codebase, which is worrying, how this project is meant to be supported and go forward?  If there is no development resources allocated to evolve storage drivers, maybe worth reexporting everything from docker graphdrivers?

Example of missing PRs are : 
 -  https://github.com/moby/moby/pull/23497
 -  https://github.com/moby/moby/pull/26212

**Comment by rhatdan** [comment]
How timely.  We have been working on forward patching stuff from moby this week.
https://github.com/containers/storage/pull/98
https://github.com/containers/storage/pull/105
https://github.com/containers/storage/pull/100

So yes we plan on staying up to date with any changes/bug fixes there.

**Comment by rhatdan** [comment]
Right now we have been concentrating on Overlay driver (overlay2 in Moby).  But we plan on adding more support for devicemapper and perhaps replacing it with a new lvm based driver going forward.

**Comment by rhatdan** [comment]
These have been all back ported, I believe.
