### ISSUE TITLE
`ChownPathByMaps` collapses UIDs when container UID 0 is mapped to non-zero host UID that also appears in the image

### ISSUE THREAD

**Issue by jfroy** [containers/storage#1056]
`ChownPathByMaps` has a surprising (to me) behavior when creating a container with a UID map that maps container UID 0 to a non-zero host UID from a container image with files owned by both UID 0 and that non-zero UID.

As a simple example, imagine a system image where most nodes are owned by UID 0, with a few files owned by UID 1000 (say by virtue of running `useradd` in the Containerfile).

If you run this image with rootfull Podman using `--uidmap=0:1000:1 --uidmap=1:100000:65536`, which looks like the map you could get from rootless Podman, you'll end up with a container where all the nodes owned by UID 0 _and_ the nodes owned by UID 1000 in the image will be owned by host UID 1000 (container UID 0). I was expecting the nodes owned by UID 1000 in the container image to be mapped to host UID 100999 in the container.

Looking at the code, `ChownPathByMaps` (really, `platformLChown` in `chown_unix.go`) seem to assume container images have _host_ UIDs (and GIDs), so it first maps them to container IDs then back to host IDs using the container's maps. It makes more sense to me that UIDs in container images should be treated as container UIDs up-front.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
this PR seems to fix the issue: https://github.com/containers/storage/pull/1057

I've no idea why it was originally checking for the `RootPair()`.  Let's see if it breaks anything in the CI
