### ISSUE TITLE
Pulling image fails with operation not permitted when unprivileged

### ISSUE THREAD

**Issue by EvgenyAGRO** [containers/storage#1095]
I've implemented custom client that is able to pull images, it is implemented using `containers/storage` lib (in a similar fashion to `podman`).  
Most of the times I am able to pull images successfully. 
Although when trying to pull some images in an **unprivileged** pod (with **MKNOD** caps) on **OpenShift v4.7** I get:
```
Error committing the finished image: error adding layer with blob: Error processing tar file(exit status 1): operation not permitted
```
When I run the pod in privileged mode everything is working fine.  

Running `strace` on the client in unprivileged pod showed the following when an image failed:
```
547325 newfstatat(AT_FDCWD, "/etc/yum.repos.d/.wh.redhat.repo",  <unfinished ...>
547325 <... newfstatat resumed>0xc000c22378, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
547325 mknodat(AT_FDCWD, "/etc/yum.repos.d/redhat.repo", S_IFCHR|000, makedev(0, 0) <unfinished ...>
547325 <... mknodat resumed>)           = -1 EPERM (Operation not permitted)
547325 write(2, "operation not permitted", 23 <unfinished ...> 
```
It looks like it's failing on recreation of whiteout files using `MKNOD`.
After checking similar issues on podman github, I made sure that `fuse-overlayfs` is installed.

Without going too much into the code, I want to note that I'm always using the following store:
```
store, err := storage.GetStore(storage.StoreOptions{
		GraphDriverName: "overlay",
		GraphRoot:       opt.storagePath,
		RunRoot:         opt.runtimePath,
	})
```

After digging in `containers/storage` lib, I saw that there is a built-in function called `getRootlessStorageOpts `, I saw slightly different logic there:
```
if path, err := exec.LookPath("fuse-overlayfs"); err == nil {
		opts.GraphDriverName = "overlay"
		opts.GraphDriverOptions = []string{fmt.Sprintf("overlay.mount_program=%s", path)}
	}
```
Do I always need to pass `fuse-overlayfs` as mount_program when I'm rootless? It's strange because some images are pulled successfully without explicitly setting it.

Does anyone have an idea what could be the problem? Does it make sense that although pod has `MKNOD` caps, the client still fails with `EPERM` on `MKNOD`? I know it's a bit abstract but maybe I'm missing something trivial.

**Additional notes:**
Fails also with SELinux disabled, nothing special in audit log or dmesg, it doesn't look like something particular is blocking it.

**Comment by giuseppe** [comment]
you are creating a whiteout file.  Is overlay the underlying file system where you are trying to create it?

If so, it is overlay to block creation of whiteout files, even if you have MKNOD

**Comment by EvgenyAGRO** [comment]
@giuseppe Yes I’m using overlay. But why would overlay block? I mean it is supposed to work with `fuse-overlayfs` no? Should i explicitly set fuse-overlayfs as mount program or something?
I mean that’s how podman does it in rootless mode no?

**Comment by EvgenyAGRO** [comment]
Also could anyone maybe briefly explain why overlay blocks mknod even if `MKNOD` caps are present?

**Comment by rhatdan** [comment]
Are you sure you have CAP_MKNOD?  Are you running rootfull or rootless?  If rootless how are you getting CAP_MKNOD?

**Comment by EvgenyAGRO** [comment]
@rhatdan Yes, I'm running the process in openshift pod with security context, when running `oc describe scc` I get the following settings:
```
Settings:  
Allow Privileged:                               false  
Allow Privilege Escalation:               true  
Default Add Capabilities:                  <none>  
Required Drop Capabilities:              <none>  
Allowed Capabilities:                         NET_ADMIN,NET_RAW,SYS_ADMIN,SYS_PTRACE,SYS_CHROOT,MKNOD,SETFCAP  Allowed Seccomp Profiles:               <none>  
Allowed Volume Types:                   *  
Allowed Flexvolumes:                      <all>  
Allowed Unsafe Sysctls:                 <none>  
Forbidden Sysctls:                          <none>  
Allow Host Network:                       true  
Allow Host Ports:                            true  
Allow Host PID:                               true  
Allow Host IPC:                               false  
Read Only Root Filesystem:           true  
Run As User Strategy: RunAsAny    
UID:                                        <none>    
UID Range Min:                              <none>    
UID Range Max:                              <none>  
SELinux Context Strategy: RunAsAny    
User:                                       <none>    
Role:                                       <none>    
Type:                                       <none>    
Level:                                      <none>  
FSGroup Strategy:                 RunAsAny    
Ranges:                                   <none>  
Supplemental Groups Strategy: RunAsAny    
Ranges:                                     <none>
```

To make sure I also SSHed to the pod and got caps of the running process:
```
0x00000000882c35fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_mknod,cap_setfcap
```

I can clearly see that process is running with `cap_mknod`.
I am running with `Allow privileged = false` so I assume it is considered rootless(?) but with added capabilities.

**Comment by EvgenyAGRO** [comment]
@rhatdan I should also note that running openshift pod in privileged mode (`Allow privileged = true`) does work as expected. Also I've stumbled upon an interesting comment in OpenShift 4.7 documentation of CI/CD pipelines with Buildah:
```
In addition, the Buildah cluster task, shipped as part of the OpenShift Pipelines, uses vfs as the default storage driver.

If you do not use the vfs storage driver, configure the service account associated with the task run or the pipeline run to have a privileged SCC, and set the security context as privileged: true.
```

Although it's not exactly the same, I believe it might be related. In fact, when using `vfs` storage driver it works as expected as well (as it doesn't use MKNOD as per my understanding).

So it makes me believe that it is something Red Hat/OpenShift related that is tampering.

**Comment by rhatdan** [comment]
If that would could  you just get a volume to be mounted at $HOME/.local/share/containers or /var/lib/containers?

**Comment by rhvgoyal** [comment]
Yes overlay filesystem denies creation of whiteout objects. It does not matter you have the capability or not.

static int ovl_mknod(struct user_namespace *mnt_userns, struct inode *dir,
                     struct dentry *dentry, umode_t mode, dev_t rdev)
{
        /* Don't allow creation of "whiteout" on overlay */
        if (S_ISCHR(mode) && rdev == WHITEOUT_DEV)
                return -EPERM;

        return ovl_create_object(dentry, mode, rdev, NULL);
}

And I think reason is that overalyfs uses whiteout nodes to keep track of unlinked files. So it does not want users to be able to write whiteout files giving the impression that file has been unlinked.

**Comment by EvgenyAGRO** [comment]
@rhatdan Thanks, I'll try that. There is one thing I didn't mention, there are certain OpenShift environments in which it does work unprivileged, the difference is mainly minor version of OpenShift (probably underlying kernel version as well). Do you think it can also be related to device cgroup? When running unprivileged pod, we might have device cgroup access restriction to devices. The environment in which I can reproduce the issue the file `/sys/fs/cgroup/devices/devices.list` is missing so I'm not sure what device cgroup it inherits. Another environment in which it works fine with unprivileged, it looks like device cgroup `/sys/fs/cgroup/devices/devices.list` appears and contains `c *:* m` and looks fine.

**Comment by rhatdan** [comment]
Device Cgroup would come into play denying you from creating certain devices.

**Comment by EvgenyAGRO** [comment]
@rhvgoyal I'm not sure what you mean. Whiteout files creation I'm talking about are part of overlayfs. I'm using `storage/containers` store functionality with `overlay` graph storage driver that I suppose under the hood manages overlayfs.

**Comment by rhatdan** [comment]
Is the overlay on an overlay?  This is not allowed.

**Comment by EvgenyAGRO** [comment]
@rhatdan @rhvgoyal Sorry if I'm confused anyone, I don't use overlay on an overlay. Overlay is on XFS. I just meant that I'm not arbitrarily creating character device files with MKNOD, just using `containers/storage` lib with "overlay" storage driver which I guess is the one creating whiteout files using MKNOD.

**Comment by giuseppe** [comment]
Is it running inside of a container though?  Can you share the content of `cat /proc/self/mountinfo`?

**Comment by EvgenyAGRO** [comment]
@giuseppe Yes it's running inside a container. The process is running inside container inside OpenShift pod. I will add the content later.

**Comment by giuseppe** [comment]
So unless you configure and use a volume, you are writing on overlay.  The overlay fike system blocks creating a whiteout file.  You need to make sure the underlying file system is not overlay and you can do that with a volume

**Comment by EvgenyAGRO** [comment]
@giuseppe I mount a volume from the host, it has XFS filesystem (also verified with mtab), and storage path for the overlay driver is on that mounted volume. So I don’t think I overlay on top of overlay.

**Comment by giuseppe** [comment]
> @giuseppe I mount a volume from the host, it has XFS filesystem (also verified with mtab), and storage path for the overlay driver is on that mounted volume. So I don’t think I overlay on top of overlay.

ok thanks for verifying that.  So the reason why it fails is because you miss CAP_MKNOD.

containers/storage has a check for creating a whiteout before using native overlay (since it is required for whiteout files).

Could you debug why `SupportsNativeOverlay` is reporting it is supported in your case?

Is the storage empty when you attempt the pull or are you reusing an existing one?

In the latter case, it might be reading the value of `$STORAGE/overlay/.has-mount-program` and skipping the check.

**Comment by EvgenyAGRO** [comment]
@giuseppe I realized that I was running an outdated version of `containers/storage` (v1.13.4) that is missing `SupportsNativeOverlay `, I guess it might be also part of the problem (at least I could have some warnings). Unfortunately I currently don't have access to the env where it is reproducible, I will update as soon as I'll run the suggested checks. Thanks, appreciate the help!

**Comment by giuseppe** [comment]
@EvgenyAGRO any update on this issue?

**Comment by EvgenyAGRO** [comment]
Unfortunately it's some remote env I currently don't have access to. I will meanwhile close the issue, when I'll have an input and if it will be relevant, I will reopen. Thanks for help!
