### ISSUE TITLE
Error : panic: inconsistency - windowsfilter graphdriver should not be used when in LCOW mode

### ISSUE THREAD

**Issue by ceddup** [containers/storage#1125]
Context : 
Windows server 2019
Docker Enterprise Edition Preview
I'm trying to run Linux Container On Windows 
The Docker service doesn't start.
And when I run 
`dockerd --debug --experimental`
I get this error:
panic: inconsistency - windowsfilter graphdriver should not be used when in LCOW mode
Since this error seams to come from
https://github.com/containers/storage/blob/main/drivers/windows/windows.go
I figured I should asked here but I might as well not be in the right place at all. If so, please excuse me.

**Comment by rhatdan** [comment]
Docker does not use containers/storage, so not sure what is going on here.

**Comment by mtrmac** [comment]
@ceddup Is there anything to suggest this is involving a code from containers/storage? At the very least full version numbers and a complete debug log?

(OTOH Docker seems to have removed that message in https://github.com/moby/moby/pull/34642 , back in 2017, so it’s really not obvious what is going on.)

**Comment by ceddup** [comment]
Oh my this happened quite a long time ago now. It happened on a test server that doesn't exist anymore so I can't give you anymore informations on that. Sorry, feel free to close this issue of course. Have a good day.

**Comment by mtrmac** [comment]
Thanks for the confirmation.
