### ISSUE TITLE
error initializing: chown <PATHTOGRAPHROOT>/storage/graphroot/overlay/l: operation not permitted

### ISSUE THREAD

**Issue by vocaltract** [containers/storage#1129]
I found that in `<PATHTOPROJECT>/storage/drivers/overlay/overlay.go`, this file has following function
```go
func Init(home string, options graphdriver.Options) (graphdriver.Driver, error) {
......
  rootUID, rootGID, err := idtools.GetRootUIDGID(options.UIDMaps, options.GIDMaps)
  if err != nil {
  return nil, err
  }
  
  // Create the driver home dir
  if err := idtools.MkdirAllAs(path.Join(home, linkDir), 0700, rootUID, rootGID); err != nil {
  return nil, err
  }
......
}
```

Here it maps the uid and gid and try to `chown` a dir in `idtools.MkdirAllAs`.
I found it impossible to perform a `chown` without root privilege, which lead to failure of initialization.
Should this project always run with root privilege? Or I have some misunderstanding? 

This is the first time I try to open an issue and I'm not a English native speak. I feel sorry for my expression.

**Comment by nalind** [comment]
Yes, it should be running as UID 0.  This can be in a user namespace where UID 0 inside of the namespace is mapped to some other UID outside of the namespace.
