### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by lonnietc** [containers/storage#1163]
Hi All,

I have been on the search for some type of container file system that would allow me to set up a storage in which I can place 8 databases on the inside but which would only be 1 total image on the outside.

Then, I could attach the image to my application and access the databases from within the application.

Of course, this would not be using docker, or other engine but directly attaching the storage to my application and then accessing the files from within which may grow/shrink based upon use.

Could this container "storage" library help?

My thoughts are that it would be like creating a single dataset container and having my needed files within it.

Any thoughts or suggestions would be greatly appreciated.

**Comment by giuseppe** [comment]
so are you looking for a way to "merge" 8 images into a single container?

I think you may need buildah instead of using the `containers/storage` library

**Comment by giuseppe** [comment]
I am closing the issue since it doesn't look like a problem we need to take care of, but please feel free to keep the discussion going and add more comments
