### ISSUE TITLE
Bug: Get Storage with "overlay2" driver but return "overlay" driver

### ISSUE THREAD

**Issue by cospotato** [containers/storage#1168]
I get a storage instance with the code below. I prefer to get a storage with `overlay2` driver. The `GetStorage` actually created the correct dirs. But returned wrong driver.

```golang
opts := storage.StoreOptions{
    RunRoot:         "/run/demo/images",
    GraphRoot:       "/var/lib/demo/images",
    GraphDriverName: "overlay2",
}

stg, err := storage.GetStore(opts)
if err != nil {
    log.Fatal(err)
}
```

I trace down the code. And i found this function return the driver with the name constantly.

https://github.com/containers/storage/blob/845808c3fcc81f89a860b6ddd0302200154f8d43/drivers/overlay/overlay.go#L383-L395

This cause Error in the program below.

```golang
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/containers/common/libimage"
	"github.com/containers/storage"
	"github.com/containers/storage/pkg/reexec"
)

func main() {
	if reexec.Init() {
		return
	}

	opts := storage.StoreOptions{
		RunRoot:         "/run/demo/images",
		GraphRoot:       "/var/lib/demo/images",
		GraphDriverName: "overlay2",
	}

	stg, err := storage.GetStore(opts)
	if err != nil {
		log.Fatal(err)
	}

	runtime, err := libimage.RuntimeFromStore(stg, &libimage.RuntimeOptions{})
	if err != nil {
		log.Fatal(err)
	}

	images, err := runtime.Load(context.Background(), "./archive.tar", &libimage.LoadOptions{})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(images)

	err = runtime.Save(context.TODO(), images, "docker-archive", "./image.tar", &libimage.SaveOptions{})
	if err != nil {
		log.Fatal(err)
	}
}

```

```console
[docker.io/library/ubuntu:latest docker.io/library/alpine:latest]
2022/03/17 13:12:01 reading blob sha256:8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759: 1 error occurred:
        * creating file-getter: readlink /var/lib/smartx/images/overlay/8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759/diff: no such file or directory

exit status 1
```

**Comment by flouthoc** [comment]
Hi @cospotato , I think in instances of `c/storage` the `overlay2` is automatically swapped with `overlay` at few places. Could you explain what are you try to do ? Just to try something out does it work for you if you hardcode it to `overlay2` https://github.com/containers/storage/blob/main/drivers/overlay/overlay.go#L384 ?

**Comment by giuseppe** [comment]
yes, containers/storage has only one overlay driver (that is the equivalent of overlay2 in Docker), so overlay and overlay2 are treated in the same way.

**Comment by cospotato** [comment]
Hi @flouthoc , I'm trying to integrate this to my project. I need a mechanism to load and save multi images. The code in the description is just a demo.

**Comment by cospotato** [comment]
@giuseppe OK，Thank you for your reply.
