### ISSUE TITLE
pkg/mount.Mounted() gets false positives on hidden mounts

### ISSUE THREAD

**Issue by nalind** [containers/storage#127]
The implementation of `Mounted()` in `pkg/mount` doesn't take into account the possibility of the location that it's checking having been mounted, and then another filesystem having been mounted over one of its parent directories.  When that happens, the checked location is still listed in `/proc/self/mountinfo`, but subsequent attempts to manipulate mount flags or unmount it will fail.

The [solution](https://github.com/projectatomic/bubblewrap/pull/118) that [bubblewrap](https://github.com/projectatomic/bubblewrap/) uses looks like a good one: it walks the list of mounts, groups them by parent ID, and prunes out any that are "hidden" by virtue of being a subdirectory (say, /foo/bar) of another mountpoint (/foo) that has the same parent.  This follows from knowing that if the subdirectory (/foo/bar) had been mounted later (and therefore, was not hidden), its parent ID would be the ID of the mountpoint of which it is a subdirectory (/foo).

That done, we can start at the mount ID for `/` (or the last one, if there's more than one), and either gather the full list of mounts by walking its list of mounts and using their IDs to find additional lists of mounts, or search as though we were walking a filesystem, finally either finding an entry for the location that we're checking, or not.

**Comment by rhatdan** [comment]
@nalind Is this something for an intern to work on this summer?

**Comment by nalind** [comment]
Sure.

**Comment by rhatdan** [comment]
@nalind I take it we still have this issue?

**Comment by rhatdan** [comment]
Since it has been two years and no action, I am closing this issue.
