### ISSUE TITLE
rawhide(f37)  + --uidmap: Unmounting error: EINVAL

### ISSUE THREAD

**Issue by edsantiago** [containers/storage#1270]
On current (2022-06-27) f37:
```console
# podman run --uidmap 0:10000:10000 quay.io/libpod/testimage:20210610 true
ERRO[0000] Unmounting /var/lib/containers/storage/overlay/89bd3d0bfb07220c3b715562c8fcad9656350522d31348125a4b5548fff541b1/merged: invalid argument 
Error: error mounting storage for container 2f987a9a5038866172185259e8543d4bd0d443c8281d1a1c63fe194f99b14f41: creating overlay mount to /var/lib/containers/storage/overlay/89bd3d0bfb07220c3b715562c8fcad9656350522d31348125a4b5548fff541b1/merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/89bd3d0bfb07220c3b715562c8fcad9656350522d31348125a4b5548fff541b1/mapped/0/l/NOGMYKSTI2JBFYP2GGCC6PHX2L,upperdir=/var/lib/containers/storage/overlay/89bd3d0bfb07220c3b715562c8fcad9656350522d31348125a4b5548fff541b1/diff,workdir=/var/lib/containers/storage/overlay/89bd3d0bfb07220c3b715562c8fcad9656350522d31348125a4b5548fff541b1/work,nodev,metacopy=on,context=\"system_u:object_r:container_file_t:s0:c96,c513\"": permission denied
```
It's not SELinux. Only error reported by journalctl is:
```
... podman[10845]: 2022-06-27 12:21:42.696031095 -0400 EDT m=+0.155750992 container create 2f987a9a5038866172185259e8543d4bd0d443c8281d1a1c63fe194f99b14f41 (image=quay.io/libpod/testimage:20210610, name=eloquent_noyce, created_at=2021-06-10T18:55:36Z, created_by=test/system/build-testimage, io.buildah.version=1.21.0)
... kernel: overlayfs: failed to resolve '/var/lib/containers/storage/overlay/89bd3d0bfb07220c3b715562c8fcad9656350522d31348125a4b5548fff541b1/mapped/0/l/NOGMYKSTI2JBFYP2GGCC6PHX2L': -13
```
podman-4.1.1-2.fc37.x86_64 + container-selinux-2.187.0-1.fc37.noarch on 5.19.0-0.rc2.21.fc37.x86_64 (caution: DO NOT USE container-selinux-2.188.0-1.fc37, it is completely broken, https://github.com/containers/container-selinux/issues/182)

Originally seen in [gating tests](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/148472/testReport/(root)/tests/root_test/) but reproduces easily on a 1minutetip VM (again, make sure you downgrade container-selinux).

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/storage/pull/1271

**Comment by brauner** [comment]
A sequence like:

```
mkdir /source /target
chmod 700 /source
chown 0:0 /source
sudo mount --bind -o X-mount.idmap="1:1000:1" /source /target
```

where [g,u]id zero isn't mapped in `/target` will mean even root can't access `/target`. This is not unique to idmapped mounts but also applies to filesystems that can be mounted inside of a user namespace in general. It's just harder to create that scenarios. This is an understood limitation. Note that the root user can still change ownership to anything [g,u]id that is mapped in `/target`, i.e. it could do `chown 1000:1000 /target`. But it can't chown back to something that isn't mapped, i.e. it can`chown 0:0 /target` as [g,u]id zero isn't mapped in `/target`. Hope that helps!
