### ISSUE TITLE
CONTAINERS_STORAGE_CONF behavior is inconsistent in rootless mode

### ISSUE THREAD

**Issue by scanon** [containers/storage#1278]
/kind bug

**Description**

When setting the CONTAINERS_STORAGE_CONF environment variable, the handling of the configuration file is inconsistent in rootless mode.  This can easily be seen if you set CONTAINERS_STORAGE_CONF to the default (e.g. $HOME/.config/containers/storage.conf) and do a podman info.  Many of the settings will no longer be honored.  At best, this behavior seems very confusing.

There was a similar issue (#10762) that was closed with a workaround but that was just for override the graphRoot.

**Steps to reproduce the issue:**

1. Create a storage configuration with some overrides such as the mount_program or additionalimagestores.

2. Run podman info -f json|jq .store

3. Run CONTAINERS_STORAGE_CONF=$HOME/.config/containers/storage.conf podman info -f json|jq .store

4. Compare the output from the two

**Describe the results you received:**

Many of the settings such as mount_program and additionalimagestores will no longer be used.

**Describe the results you expected:**

Specifying the exact same configuration file as the default using the environment variable override would result in the same behavior.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Tue Nov  9 13:23:56 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module_el8.5.0+890+6b136101.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 84384406047fae626269133e1951c4b92eed7603'
  cpus: 48
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: podman01
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1016907
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 16907
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-193.19.1.el8_2.x86_64
  linkmode: dynamic
  memFree: 19889147904
  memTotal: 211014496256
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module_el8.5.0+911+f19012f9.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/16907/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.5.0+890+6b136101.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 1675096064
  swapTotal: 2218782720
  uptime: 12262h 54m 56.79s (Approximately 510.92 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /global/homes/c/canon/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "true"
    overlay.imagestore: /global/homes/shared/storage
    overlay.mount_program:
      Executable: /global/homes/c/canon/bin/mymount
      Package: Unknown
      Version: 'mount from util-linux 2.32.1 (libmount 2.32.1: selinux, btrfs, debug)'
  graphRoot: /home/canon/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 165
  runRoot: /run/user/16907
  volumePath: /home/canon/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1636493036
  BuiltTime: Tue Nov  9 13:23:56 2021
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-9.module_el8.5.0+988+b1f0b741.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No but this is pretty recent

**Additional environment details (AWS, VirtualBox, physical, etc.):**

kvm Virtual machine running Centos 8.

**Comment by giuseppe** [comment]
opened a PR with a proposed fix: https://github.com/containers/storage/pull/1279

**Comment by rhatdan** [comment]
Yes I agree that we should use full containers.conf if set with ENV .
