### ISSUE TITLE
Question - underlying file system type

### ISSUE THREAD

**Issue by LukeMauldin** [containers/storage#1292]
I am running Kubernetes 1.22.X which is running containerd v1.5.9-k3s1 on SLES SP4 - kernel 5.14.X.  The container file systems themselves are listed as `overlay` when running `mount` but my question is: what are the pros/cons of using ext4 vs xfs vs btrfs for the mount point that serves as the root container storage location?  I am only writing minimal data into the containers themselves.  Most of the persistent data is written into external volumes mounted via the Kubernetes CSI interface.
If this is not the correct location to post this question, please refer me to some place that might be more appropriate.

**Comment by giuseppe** [comment]
the most appropriate place for containerd questions is https://github.com/containerd/containerd

The underlying file system should not matter too much, I am not aware of any difference among these when used with overlay
