### ISSUE TITLE
Suboptimal formatting of containers-storage.conf(5)

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/storage#1317]
As can be seen below the lines starting with :“zfs", wise, “In Rootless mode” are not properly indented.

Moreover, the text does not flow: each sentance is on each own line. Ideally all sentences shall be grouped in an indented paragraph and new lines shall happen when the width is not sufficient, starting indented on the next line.

![man-cont-stor](https://user-images.githubusercontent.com/4992947/187613078-dd10ac93-9018-488c-b75d-6a62af23a01a.png)

I use containers-storage.conf(5) as available on Fedora 36, that is I have not rendered and installed the  file myself.

**Comment by rhatdan** [comment]
Care to open a PR to fix the man page?
