### ISSUE TITLE
podman blob error

### ISSUE THREAD

**Issue by pushpi55** [containers/storage#1356]
Trying to build a docker image in OL8, seeing the following error after 1st step: 
bash-4.4$ docker build .
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
WARN[0000] Network file system detected as backing store.  Enforcing overlay option `force_mask="700"`.  Add it to storage.conf to silence this warning 
STEP 1/18: FROM container-registry.oracle.com/os/oraclelinux:7.7
Trying to pull container-registry.oracle.com/os/oraclelinux:7.7...
Getting image source signatures
Copying blob 5f0a070aa70d done  
Error: error creating build container: writing blob: adding layer with blob "sha256:5f0a070aa70d35717648178db6be5e4ef256af885bd370f2d2a22f2a7365012a": Error processing tar file(exit status 1): lsetxattr /: operation not supported

bash-4.4$ podman info
WARN[0000] Network file system detected as backing store.  Enforcing overlay option `force_mask="700"`.  Add it to storage.conf to silence this warning 
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module+el8.6.0+20721+d8d917a9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 226e45e4f5c8e763435ceae775bac989048f45e1'
  cpuUtilization:
    idlePercent: 99.35
    systemPercent: 0.22
    userPercent: 0.43
  cpus: 4
  distribution:
    distribution: '"ol"'
    variant: server
    version: "8.4"
  eventLogger: file
  hostname: phoenix115524
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 8500
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1651487
      size: 1
  kernel: 5.4.17-2136.306.1.3.el8uek.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 28967235584
  memTotal: 33364885504
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.6.0+20721+d8d917a9.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.12
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1651487/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+20721+d8d917a9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 18586501120
  swapTotal: 18974998528
  uptime: 3h 26m 35.46s (Approximately 0.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - container-registry.oracle.com
  - docker.io
store:
  configFile: /home/pusinha/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/pusinha/.local/share/containers/storage
  graphRootAllocated: 9223372036854775808
  graphRootUsed: 6897961795584
  graphStatus:
    Backing Filesystem: nfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1651487/containers
  volumePath: /home/pusinha/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659569779
  BuiltTime: Wed Aug  3 23:36:19 2022
  GitCommit: ""
  GoVersion: go1.17.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Comment by rhatdan** [comment]
https://www.redhat.com/sysadmin/rootless-podman-nfs
