### ISSUE TITLE
Where do the github,com/containers folks hang out?

### ISSUE THREAD

**Issue by x7upLime** [containers/storage#1453]
I'm aware there is a podman discord/irc/matrix.. 
but I found many references to a freenode channel that seems quite dead.

Now, what is the proper place to ask questions about containers/storage, containers/image, containers/common, ...?l

https://github.com/containers/storage/blob/main/CONTRIBUTING.md#communications
https://github.com/containers/image
https://github.com/containers/common/blob/e720b5cf39f50af623bfb923bba519ae2648705a/README.md
...
there are plenty of results inside the containers organization.

**Comment by rhatdan** [comment]
If you want to talk to humans Podman on discord/irc/matrix is the best place.
The same engineers work on all of these "containers" project.
