### ISSUE TITLE
【rootless】Error for non-root user

### ISSUE THREAD

**Issue by cubxxw** [containers/storage#1505]
My environment is a non-root user, I tried to implement rootless mode, but some issues occurred

https://github.com/sealerio/sealer/blob/f67d52709fcd0af0bba575b14ec003c43585f4f3/vendor/github.com/containers/storage/types/utils.go#L25

```bash
2023-02-09 11:09:47 [ERROR] [root.go:75] sealer-v0.9.0: unable to make rootless runtime: mkdir /run/user/0/containers: permission de
```

**Comment by cubxxw** [comment]
oh, I don't know why I can't use rootless runtime, how do I fix it:

https://github.com/containers/storage/blob/07d070f2844cb0f8996ebfb87cd38a7bce0530fe/types/utils.go#L23

**Comment by rhatdan** [comment]
Looks like XDG_RUNTIME_DIR is set incorrectly.  If you are running in rootless mode then you should not be using /run/usr/0 user.

**Comment by cubxxw** [comment]
I don't really understand what I should look at to learn it, or to configure it @rhatdan

**Comment by rhatdan** [comment]
Did you login as root and then su USERNAME, if yes then you don't have a true rootless mode, you have the roots $XDG_RUNTIME_DIR set.  If you login directly to the USERNAME account, then podman should work.

**Comment by giuseppe** [comment]
I am closing the issue since there was no feedback for almost 2 months
