### ISSUE TITLE
podman creates overlay* subdirs all over the filesystem

### ISSUE THREAD

**Issue by slartibart70** [containers/storage#1531]
Hi,

i copied /usr/share/containers/storage.conf to /etc/containers/storage.conf because my root partition is (too) small to hold images and containers.
The diff to the original is:
```
diff /etc/containers/storage.conf /usr/share/containers/storage.conf 
28,29c28
< # graphroot = "/var/lib/containers/storage"
< graphroot = "/home/podman/containers/storage"
---
> graphroot = "/var/lib/containers/storage"
238d236
< 
```

and yes, i set se-manage as described in `man containers-storage-conf` for this new subdir

This works ok, images get put into this new location, container-volume mounts as well 

One strange thing is, that podman creates the subdirs
overlay
overlay-containers
overlay-layers
overlay-locks

in each directory, where root called podman
A simple 'podman info' is enough to create the folders in the current dir.

Aren't they supposed to be put ONLY under the /home/podman/containers/storage dir?
If i rename my /etc/containers/storage.conf to storage.conf.xxx and we have the old /var/lib/containers/storage folder back, this behaviour is stopped immediately - the overlay* dirs only appear within /var/lib/containers

Smells like a bug?
Or did i miss something?

Client:       Podman Engine
Version:      4.4.2
API Version:  4.4.2
Go Version:   go1.19.6
Built:        Wed Mar  1 12:22:59 2023
OS/Arch:      linux/amd64

on fedora37

**Comment by slartibart70** [comment]
i wanted to workaround this problem by symlinking to /home/podman/containers/storage within /var/lib/containers/
(without the storage.conf in /etc)

and...same problem

Seems like someone really doesn't like the redirects in the code :-)

**Comment by rhatdan** [comment]
No the storage is recorded in the podman datastore.  You could remove all containers and then remove the boltdb database, and then you would not loose your images.

**Comment by slartibart70** [comment]
Thanks for the info
It seems reading your book is mandatory for podman usage :-) 
As improvement to the docs (man pages) i would suggest to place the 'podman system reset' on a more prominent place? (in man containers-storage.conf it isn't mentioned at all)

**Comment by rhatdan** [comment]
Container storage is independent of podman, so mentioning podman's use of storage seems a bit out of place.
Reading my book is always useful.  :^)
