### ISSUE TITLE
Podman v4.3.1 to 4.4.4 introduced breaking change for unsupported filesystems

### ISSUE THREAD

**Issue by tis-rpage** [containers/storage#1546]
### Issue Description

On 4.3.1 and earlier, unsupported filesystems, such as `0x53464846` for WSLFS would not abort the command and would complete the action.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run an unsupported filesystem, like WSL1 WLFS
2. Install podman 4.3.1
3. sudo podman images
4. view successful image list
5. Install podman 4.4.4
6. sudo podman images
7. view nothing, because error handling aborted on the unsupported filesystem that used to be functional yet unsupported

### Describe the results you received

```
podman images
Error: filesystem type 0x53464846 reported for /var/lib/containers/storage is not supported with 'overlay': backing file system is unsupported for this graph driver
```

### Describe the results you expected

```
podman images
REPOSITORY                                                        TAG                                           IMAGE ID      CREATED        SIZE
<none>                                                            <none>                                        b177afe92189  7 months ago   559 MB
<none>                                                            <none>                                        10a9f9f6f494  7 months ago   559 MB
quay.io/keycloak/keycloak                                         19.0.1                                        49756595a9cb  7 months ago   559 MB
gcr.io/k8s-minikube/kicbase                                       v0.0.33                                       b7ab23e98277  8 months ago   1.15 GB
```

### podman info output

```yaml
podman info --log-level=trace
INFO[0000] podman filtering at log level trace
DEBU[0000] Called info.PersistentPreRunE(podman info --log-level=trace)
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /var/lib/containers/storage
DEBU[0000] Using run root /run/containers/storage
DEBU[0000] Using static dir /var/lib/containers/storage/libpod
DEBU[0000] Using tmp dir /run/libpod
DEBU[0000] Using volume path /var/lib/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Unknown filesystem type 0x53464846 reported for /var/lib/containers/storage
Error: filesystem type 0x53464846 reported for /var/lib/containers/storage is not supported with 'overlay': backing file system is unsupported for this graph driver
DEBU[0000] Shutting down engines
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Running as root on WSL1 alpine linux.

### Additional information

Issue seems related to this pull request:
Update c/storage after https://github.com/containers/storage/pull/1436

As the issue affects the latest versions of buildah and skopeo, suggesting a change in error handling in c/images is impacting all 3 products. A possible fix would be to add type 0x53464846 as "WSLFS" as a supported filesystem to bypass the error handling.

**Comment by giuseppe** [comment]
I think the issue is caused by d9da33511d01d26ff4d791cd8ce8d2f6c04a9b65.

I am fine with reverting the change, I am usually against these overzealous checks that block valid use cases.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/storage/pull/1547

**Comment by aarontomlin** [comment]
b

> I think the issue is caused by [d9da335](https://github.com/containers/storage/commit/d9da33511d01d26ff4d791cd8ce8d2f6c04a9b65).
> 
> I am fine with reverting the change, I am usually against these overzealous checks that block valid use cases.

Hi Giuseppe,

If I understand correctly, since the backing filesystem is not supported with OverlayFS it would not be safe to continue.
Why not provide actual support instead - assuming this is possible?

**Comment by TomSweeneyRedHat** [comment]
@giuseppe @rhatdan is this something we need to get into ZeroDay for RHEL 8.8/9.2?  It smells like it.....
