### ISSUE TITLE
additionalimagestores option ignored in /etc/containers/storage.conf

### ISSUE THREAD

**Issue by phemmer** [containers/storage#1591]
When running rootless, the `additionalimagestores` option is ignored unless it's in the user's `~/.config/containers/storage.conf`. The setting in `/etc/containers/storage.conf` is ignored, and only applies to root.

I'm not sure if this is a bug, or deliberate behavior. If deliberate, it is very unintuitive, as `/etc` is typically used for shared configuration. For settings which should only apply to root, I would expect this setting to live in `/root/.config/containers/storage.conf`.
[The documentation](https://github.com/containers/storage/blob/main/docs/containers-storage.conf.5.md) even says:
> rootless users can create a storage.conf file to override the system storage.conf

Implying that the system storage.conf (`/usr/share` or `/etc`) is applied.

This is also not an issue of the other statement in the documentation that:
> Container engines run by users with a storage.conf file in their home directory do not use options in the system storage.conf files.

I am testing with no `storage.conf` in the user's home directory.

From searching on the subject, I've found many issues about other settings also being ignored unless they're in the user's home directory. So if this is expected behavior, I think the documentation needs to identify which options are only applicable to root. I would also think there needs to be a mechanism to not completely ignore the shared `storage.conf` one the file is created in the user's home directory. The whole point of putting the setting in `/etc` is to share it, and not require every user to redefine it.

Tested with podman version 4.4.2

**Comment by rhatdan** [comment]
The problem is an additional store that is now owned by the users namespace is not going to be usable for the most part unless you use fuse-overlayfs.
Currently we can not shift the UIDmap of the root owned files into something that could be used by the user.
