### ISSUE TITLE
Make it easier to tell that our consumers aren't dockerd

### ISSUE THREAD

**Issue by nalind** [containers/storage#16]
Since we started out as a branch of docker, the graph drivers and test logic frequently use the string "docker" when constructing file names and process titles.  If a package that consumes this package is deployed on a system that's also running dockerd, I expect it'll be at least a bit confusing when monitoring processes and examining files.

**Comment by rhatdan** [comment]
@nalind I believe we have cleaned a lot of this up, can we close this issue?
