### ISSUE TITLE
RFC: remove devmapper driver

### ISSUE THREAD

**Issue by kolyshkin** [containers/storage#1619]
It seems that no one is using devicemapper storage driver nowadays, since overlayfs is so much better.

Can it be deprecated and removed? I see that moby/moby did that recently.

**Comment by rhatdan** [comment]
Makes sense to me.
@nalind @rhvgoyal @vrothberg @giuseppe @mtrmac @saschagrunert WDYT?

**Comment by giuseppe** [comment]
yes, I agree, let's drop old unmaintained stuff

**Comment by saschagrunert** [comment]
I agree we should remove it if nobody maintains it any more.

**Comment by vrothberg** [comment]
SGTM :+1:
