### ISSUE TITLE
Tests w/ go 'stable' fails

### ISSUE THREAD

**Issue by cevich** [containers/storage#164]
I'm guessing that, at some point, it will become desirable to support newer versions of go, so I'm preemptively opening this issue :smile:  The test-failure should be reproducible by executing ``hack/run_ci_tests.sh`` locally.  In travis, it's done by un-commenting this in ``.travis.yml``:

```yaml
        - GO_VERSION="stable"
          DISTRO="ubuntu"
```

I can't quite tell from the output exactly what the problem is, the build appears to complete successfully.
It could easily be caused by something not setup properly in the environment.  Here's what travis shows:

[travis_log.txt](https://github.com/containers/storage/files/1838723/travis_log.txt)

Any ideas what could be in need of fixing to make this work?

**Comment by rhatdan** [comment]
@cevich Can we close this issue since the above PR Got merged?
