### ISSUE TITLE
Doesn't support /var/lib/containers/storage as a symlink?

### ISSUE THREAD

**Issue by cgwalters** [containers/storage#165]
I try to separate my "OS partition" and my `/var/home` from my `/srv` (really `/var/srv`) which has things that I can rebuild or redownload from the Internet. Things like my git repositories as well as VM/container images.

Today I have:
```
ls -alZ /var/lib/docker
lrwxrwxrwx. 1 root root system_u:object_r:container_var_lib_t:s0 13 Nov 23 16:18 /var/lib/docker -> ../srv/docker
```

Which works fine.

I tried the same with:
```
ls -alZ /var/lib/containers/storage
lrwxrwxrwx. 1 root root unconfined_u:object_r:container_var_lib_t:s0 28 Mar 28 11:08 /var/lib/containers/storage -> ../../srv/containers-storage
```

But now I get:
```
/build-base.sh registry.fedoraproject.org/fedora:27 cgwalters/fdev
+ base=registry.fedoraproject.org/fedora:27
+ prefix=cgwalters/fdev
++ buildah from registry.fedoraproject.org/fedora:27
+ ctr=fedora-working-container-2
+ bldr sed -i /tsflags=nodocs/d /etc/dnf/dnf.conf
+ buildah run fedora-working-container-2 -- sed -i /tsflags=nodocs/d /etc/dnf/dnf.conf
/var/lib/containers/storage/overlay/2f1767021121156895fe050bb92dda17ffba1ea1e8997a396fecde7296cee4d4/merged is not an absolute path or is a symlink
```

However, a bind mount does work.

**Comment by cgwalters** [comment]
Migrated from https://github.com/projectatomic/libpod/issues/562

**Comment by giuseppe** [comment]
I think the error is coming straight from runc that doesn't like symlinks in the rootfs.  In podman we needed https://github.com/projectatomic/libpod/commit/7e3c0d493e1afbae284071643d1a46c571776a04 for solving the same issue with rootless containers on CoreOS

**Comment by rhatdan** [comment]
@giuseppe Could you open a PR for buildah to fix this.

**Comment by giuseppe** [comment]
the new intermediate mount namespace seems to solve the error for Buildah, the symlink is solved when the bind mount is created.  @cgwalters are you still seeing this error with an updated buildah?

**Comment by giuseppe** [comment]
can this be closed?
