### ISSUE TITLE
imagestore is not documented in containers-storage.conf(5)

### ISSUE THREAD

**Issue by nm004** [containers/storage#1716]
### Issue Description

According to podman(1),
```
   --imagestore=path
       Path  of the imagestore where images are stored.  By default, the storage library stores all
       the images in the graphroot but if an imagestore is provided, then the storage library  will
       store newly pulled images in the provided imagestore and keep using the graphroot for every‐
       thing else. If the user is using the overlay driver, then the images which were already part
       of the graphroot will still be accessible.

       This  will  override  imagestore  option in containers-storage.conf(5), refer to containers-
       storage.conf(5) for more details.
```

But `imagestore` is not mentioned in containers-storage.conf(5) at all.

### Steps to reproduce the issue

1. `man podman`
2. `man containers-storage.conf`

### Describe the results you received

`imagestore` is not documented in containers-storage.conf(5)

### Describe the results you expected

`imagestore` is documented in containers-storage.conf(5) if it's effective.

### podman info output

```yaml
OS: Fedora 38
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by rhatdan** [comment]
Closing issue, continue the conversation here.

**Comment by nm004** [comment]
The package in Fedora has not include the changes of this repo, so it did not appear in my system. I'm sorry for disturbing. Thank you for support.
