### ISSUE TITLE
overlay driver not being registered

### ISSUE THREAD

**Issue by haircommander** [containers/storage#1721]
@sohankunkerkar has this very weird issue where the overlay driver is not being registered. 

The node is fedora 38, containers-common is installed, and he's trying to run cri-o. He gets this error:
```
FATA[2023-09-25 12:42:26.293445305-04:00] validating root config: failed to get store to set defaults: failed to GetDriver graph overlay  /var/lib/containers/storage: driver not supported  file="crio/main.go:455"
```

digging a bit deeper, I can add a print statement above [this](https://github.com/containers/storage/blob/main/drivers/overlay/overlay.go#L148) line and get no results, while I can do the same above the [aufs](https://github.com/containers/storage/blob/main/drivers/aufs/aufs.go#L70) driver and get output.

hit this with golang 1.21.1 and 1.20.8, on cri-o main (c/storage [1.50.2](https://github.com/cri-o/cri-o/blob/main/go.mod#L29)) and  1.28.1 (c/storage [1.49.0](https://github.com/cri-o/cri-o/blob/release-1.28/go.mod#L30))

Has anyone seen this issue before/have any debugging tips?

**Comment by nalind** [comment]
In `drivers/register`, each driver has a corresponding `init()` that adds it to the list of known drivers.  The one for overlay depends on cgo and only builds for Linux, and only if the "exclude_graphdriver_overlay" build tag isn't used.  It doesn't have external dependencies, so the build tag is unlikely to be the issue, but if someone's building from source, trying to not use cgo might be relevant.

**Comment by haircommander** [comment]
ah so it seems something is wrong with the golang installation, as removing the `cgo` tag (and fussing a bit with  quota support) allows cri-o to move forward...

**Comment by haircommander** [comment]
ah! we installed golang without `gcc-go` installed, so cgo wasn't enabled, which fixed this!
