### ISSUE TITLE
`podman image mount` issue when additional image stores are used

### ISSUE THREAD

**Issue by mvo5** [containers/storage#1779]
We ran into a quite vexing issue when building a relatively simple stage for image-builder [0]. The code below copies a container ` ghcr.io/ondrejbudai/bootc:fedora` in our tests into a `/tmp/$tmpdir` image store and then uses that image store in /tmp to mount the image using `podman --imagestore /tmp/$tmpdir image mount ...`.  The issue is that in that setup the final layer of the image (which in this case contains a modified /usr/bin/bootc file) is missing and the "old" bootc file is in the mounted path but not the expected one.

After some debugging it turns out that the way the final mount call is generated is incorrect for the case of additional storages. It will generate something like:
```
lowerdir=/var/lib/containers/storage/overlay/8d72fb04445c9b041287bf1aa467de4bb8a95fb2795bb6fbe214aee32f8f1cd0/diff:/tmp/tmpy7x_x8wm/overlay/l/EWJCNVO7BXHKURAPHEKM3HOTFC:....
```
however the `/var/lib/containers/storage/overlay/8d72fb04445c9b041287bf1aa467de4bb8a95fb2795bb6fbe214aee32f8f1cd0/diff` dir is empty because the actual data is stored in   /tmp/tmp7x... and the "normal" store does not contain any data.

Attached is a small patch that works for my test-case in image-builder (and the "normal" case seems to be still working fine when running this manully) - unfortunately I do not have a better reproducer then running it with the image builder commit below right now also sorry that e patch needs `-p4` to be applied, I tested it directly in a build podman, I hope this bugreport and the diff are still useful.

[extra-storage.diff.txt](https://github.com/containers/storage/files/13708315/extra-storage.diff.txt)

Thanks!
 Michael

[0] https://github.com/ondrejbudai/osbuild/commit/6d7d411b0c4f6d3ab5d8cd06745ff2204bdb5f0f#diff-2b1fc5cd8b2ebf1d121181a2570dff7a923f476fd8a9e6c928c9f9f7085d8f8fR34

**Comment by rhatdan** [comment]
Please open a PR for us to review.
@giuseppe @nalind PTAL

**Comment by mvo5** [comment]
> Please open a PR for us to review. @giuseppe @nalind PTAL

Thanks a lot for your quick reply. As suggested I opened a PR.
(fwiw I didn't right away because my change does not contain a test and opening a PR without a test makes me uneasy :)

**Comment by mvo5** [comment]
Here is a standalone reproducer that fails with current containers/storage. As you can see from the script there are two layers and both contain "file1". When mounting the content of the lower layer is availalbe which is incorrect, it should be the upper layer. I hope this helps, There should be no external depedencies for this helper except podman/skopeo and pytest.

[reproducer-issue1179.py.txt](https://github.com/containers/storage/files/13719964/reproducer-issue1179.py.txt)
