### ISSUE TITLE
Error: 'O_PATH' undeclared in unshare.c

### ISSUE THREAD

**Issue by shikharish** [containers/storage#1788]
[Reference issue from checkpoint-restore](https://github.com/checkpoint-restore/checkpointctl/issues/112)
As mentioned in the issue above, when try to build, it gives me the following error:

```
# github.com/containers/storage/pkg/unshare
unshare.c: In function 'try_bindfd':
unshare.c:196:30: error: 'O_PATH' undeclared (first use in this function)
  196 |         ret = open(template, O_PATH | O_CLOEXEC);
      |                              ^~~~~~
unshare.c:196:30: note: each undeclared identifier is reported only once for each function it appears in
unshare.c: In function 'copy_self_proc_exe':
unshare.c:236:24: error: 'SYS_memfd_create' undeclared (first use in this function); did you mean 'SYS_timerfd_create'?
  236 |         mmfd = syscall(SYS_memfd_create, exename, (long) MFD_ALLOW_SEALING | MFD_CLOEXEC);
      |                        ^~~~~~~~~~~~~~~~
      |                        SYS_timerfd_create
make: *** [Makefile:36: checkpointctl] Error 1
```

System details:
OS: Linux Mint 21.1 x86_64
Kernel: 6.5.0-14-generic
CPU: 11th Gen Intel i5-11320H (8) @ 4.500GHz

**Comment by rhatdan** [comment]
This looks like it is defined in fcntl.h

/usr/include/asm-generic/fcntl.h:#ifndef O_PATH
/usr/include/asm-generic/fcntl.h:#define O_PATH		010000000

rpm -qf /usr/include/asm-generic/fcntl.h
kernel-headers-6.6.3-200.fc39.x86_64

Not sure which kernel first defined it.

grep -r SYS_memfd_create /usr/include/
/usr/include/bits/syscall.h:# define SYS_memfd_create __NR_memfd_create

 rpm -qf /usr/include/bits/syscall.h
glibc-headers-x86-2.38-14.fc39.noarch

**Comment by shikharish** [comment]
@rhatdan It is defined in `fcntl.h` in my system too. Although `syscall.h` is located at `/usr/include/syscall.h` in my system.

**Comment by rhatdan** [comment]
Is O_PATH  defined somewhere?  You could add a block to unshare.c to handle O_PATH with

#ifndef O_PATH
#define O_PATH 010000000
#endif

**Comment by shikharish** [comment]
Yes O_PATH is defined in `fcntl.h` in the same way:
```
#ifndef O_PATH
#define O_PATH		010000000
#endif
```

**Comment by rhatdan** [comment]
Then I don't understand why it is not compiling, unless we are not including the file correctly.

**Comment by giuseppe** [comment]
looks like some misconfiguration on your system, since `fcntl.h` has the symbol and we are including it.  Please reopen if mistaken
