### ISSUE TITLE
podman extremely slow on raspberry pi 4

### ISSUE THREAD

**Issue by endlisnis** [containers/storage#1805]
When running podman on a raspberry pi 4 (running the most recent OS -- based on Debian 12).  By default, it is EXTREMELY slow.  Almost 10x slower than docker doing a similar task:

Details here: https://github.com/containers/podman/discussions/21111

The short version of that story was: The storage driver was not set, and thus it was defaulting to vfs; which is (apparently) 10x slower than overlay on a raspberry pi.

After I changed the storage driver to overlay, things got reasonably fast again.  But, the question is, why is vfs the default?  Even as a reasonably technical person, I initially concluded that podman just had terrible performance and I moved on with docker.

If the storage driver is not set, why not check to see if overlay is available, and if it's not, then fall back to vfs?

That would create a MUCH better user experience.

**Comment by rhatdan** [comment]
@nalind @giuseppe Why do we still default to vfs, can't we check if overlay is supported and then use it, if driver is not set, then fail over to VFS.

**Comment by endlisnis** [comment]
Even on a fresh install of the OS (entire drive media re-written from ISO), I still saw vfs being used.

**Comment by giuseppe** [comment]
what podman version?

**Comment by endlisnis** [comment]
```
$ podman --version
podman version 4.3.1
```

**Comment by giuseppe** [comment]
4.3.1 doesn't have the fix, you need a newer version
