### ISSUE TITLE
overlay driver non cgo build

### ISSUE THREAD

**Issue by mech-pig** [containers/storage#1816]
According to the build tag, [registering the overlay driver requires cgo to be enabled](https://github.com/containers/storage/blob/main/drivers/register/register_overlay.go#L1), but the [overlay driver package itself seems not requiring it](https://github.com/containers/storage/blob/ac9395f2d783267fbdcf34e0ceaa3713bd042d9b/drivers/overlay/overlay_nocgo.go#L1). Is cgo really required for the overlay driver?

**Comment by rhatdan** [comment]
I don't think it is required, but users could have better performance with cgo specifically for:
// ReadWriteDiskUsage returns the disk usage of the writable directory for the ID.
// For Overlay, it attempts to check the XFS quota for size, and falls back to
// finding the size of the "diff" directory.

**Comment by mech-pig** [comment]
@rhatdan thank you for your response.

I understand that using cgo enables better performance, but my doubt is whether or not it's possible to build without cgo support in the first place. From your comment it seems it should be possible and this is also confirmed by the presence of an explicit `_nocgo` build file in the overlay package. But this is contradicted by the required `cgo` build tag in the register module and, more importantly, by the fact that the package does not build if cgo is disabled.

Here's a small example

```go
package main

import (
	"fmt"
	"os"

	graphdriver "github.com/containers/storage/drivers"

	// register the overlay graphdriver
	_ "github.com/containers/storage/drivers/overlay"
)

func main() {
	driver, err := graphdriver.GetDriver("overlay", graphdriver.Options{
		Root:          "/home/ote/.local/share/containers/storage",
		RunRoot:       "/run/users/1000/containers",
		DriverOptions: []string{"use_composefs=false"},
	})
	if err != nil {
		fmt.Println("cannot load driver:", err)
		os.Exit(1)
	}
	fmt.Println("driver succesfully loaded", driver)
}
```

with cgo enabled:
```
$ sudo CGO_ENABLED=1 go run main.go
driver succesfully loaded overlay
```

without
```
$ sudo CGO_ENABLED=0 go run main.go
# github.com/containers/storage/drivers/overlay
/root/go/pkg/mod/github.com/containers/storage@v1.52.0/drivers/overlay/overlay.go:403:16: undefined: getComposeFsHelper
/root/go/pkg/mod/github.com/containers/storage@v1.52.0/drivers/overlay/overlay.go:1588:13: undefined: mountComposefsBlob
/root/go/pkg/mod/github.com/containers/storage@v1.52.0/drivers/overlay/overlay.go:2127:25: undefined: enableVerityRecursive
/root/go/pkg/mod/github.com/containers/storage@v1.52.0/drivers/overlay/overlay.go:2132:13: undefined: generateComposeFsBlob
```

the problem seems to be [the cgo build tag in composefs](https://github.com/containers/storage/blob/d1bf4f0cf1d648fdd2e92f8841229a2da0bc3249/drivers/overlay/composefs.go#L1), [which makes the symbols defined there not being available in overlay](https://github.com/containers/storage/blob/d1bf4f0cf1d648fdd2e92f8841229a2da0bc3249/drivers/overlay/overlay.go#L404) when cgo is not enabled.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I think we need to define these functions in `overlay_nocgo.go` and do not support composefs&fs-verity without cgo

**Comment by rhatdan** [comment]
SGTM
