### ISSUE TITLE
No release for 1.52.0

### ISSUE THREAD

**Issue by alexlarsson** [containers/storage#1838]
I see there is a tag for 1.52: https://github.com/containers/storage/releases/tag/v1.52.0
But there is no release. How come?

**Comment by TomSweeneyRedHat** [comment]
I know we decided to no put c/storage v1.52.0 in Podman v4.9, but I'm not sure why a release wasn't created.  It may well have been an oversight.  @rhatdan @mheon or @nalind any concerns/objections to creating a v1.52.0 release here?  We probably ought to talk about what we want to land in v5.0 in the not too distant future too.

**Comment by rhatdan** [comment]
Sure, it is just an integer.  Containers/storage is still being worked on for zstd:chunked so not quite ready for 5.0 release yet.

**Comment by TomSweeneyRedHat** [comment]
It's alive!  https://github.com/containers/storage/releases/tag/v1.52.0

Closing.
