### ISSUE TITLE
Podman image mount: Error: layer not known

### ISSUE THREAD

**Issue by kingsleyzissou** [containers/storage#1864]
Note: This is potentially related to #1779 and we are trying to run this all in a container (and this is happening in the same stage in osbuild that @mvo5 linked to in his issue).

When trying to mount an image from a read-only image store I get the following error:
`Error: layer not known`.

Skopeo version (tried with both since #1784 only landed in skopeo after 1.14.2):
skopeo version 1.14.2
skopeo version 1.15.0-dev

Podman version (tried with both):
podman version 4.9.3
podman version 5.0.0-dev

How to reproduce:
```
sudo podman run \
    --rm \
    -it \
    --privileged \
    --security-opt label=type:unconfined_t \
    -v /var/tmp/storage:/usr/lib/containers/storage:ro \
    --entrypoint /bin/bash \
    quay.io/centos-bootc/bootc-image-builder:latest
```

Output from podman images:
```
[root@dee2e70f07d5 output]# podman images
REPOSITORY           TAG         IMAGE ID      CREATED         SIZE        R/O
localhost/testlocal  latest      64d8d8e9b20b  35 minutes ago  1.58 GB     true
```

Trying to mount `64d8d8e9b20b` results in:
Error: layer not known

So I tried exporting it to an archive and loading it again with `podman save` & `podman load` and I get:
```
[root@dee2e70f07d5 output]# podman images
REPOSITORY           TAG         IMAGE ID      CREATED         SIZE        R/O
localhost/testlocal  latest      64d8d8e9b20b  42 minutes ago  1.58 GB     false
localhost/testlocal  latest      64d8d8e9b20b  42 minutes ago  1.58 GB     true
```

Which looks good until I try:
```
[root@dee2e70f07d5 output]# podman --root /var/lib/containers/storage image mount 64d8d8e9b20b
Error: layer not known
```

And:
```
ot@dee2e70f07d5 output]# podman --root /var/lib/containers/storage rmi 64d8d8e9b20b
WARN[0000] Top layer 464743c450e3f01d8c6d0f5d1d0cbbd8046f2bd72951d77b9673f8313b1ed27e of image 64d8d8e9b20b82ace11587cd251baecda6e35be64e661f2f25de515ca878e715 not found in layer tree. The storage may be corrupted, consider running `podman system reset`.
WARN[0000] Top layer 464743c450e3f01d8c6d0f5d1d0cbbd8046f2bd72951d77b9673f8313b1ed27e of image 64d8d8e9b20b82ace11587cd251baecda6e35be64e661f2f25de515ca878e715 not found in layer tree. The storage may be corrupted, consider running `podman system reset`.
```

If I repeat the above using `skopeo copy "containers-storage:64d8d8e9b20b" "containers-storage:64d8d8e9b20b"` the outcome is exactly the same.

**Comment by giuseppe** [comment]
I think this is "fixed" by https://github.com/containers/storage/pull/1873
