### ISSUE TITLE
zstd:chunked binary footer format is broken

### ISSUE THREAD

**Issue by mtrmac** [containers/storage#1886]
Since eedd976e5b3cc4bf50c62878d8a89b85602c1f16 , AFAICS the `ReadFooterDataFromBlob` code path when parsing zstd:chunked metadata always fails, because it does not set `ChecksumAnnotation`, causing a failure when validating the manifest.

@giuseppe the binary footer seems to be unused in practice. Can we eliminate it altogether, and simplify the code?

**Comment by giuseppe** [comment]
> @giuseppe the binary footer seems to be unused in practice. Can we eliminate it altogether, and simplify the code?

what do you think if we leave the information in the file itself, but do not use in practice to pull images?

At least a layer file is self-contained and we able to retrieve the TOC, if necessary
