### ISSUE TITLE
Unreachable code in storage/drivers/overlay/overlay.go

### ISSUE THREAD

**Issue by eriksjolund** [containers/storage#1900]
Could this if statement be removed?

https://github.com/containers/storage/blob/2431799327396be3322f440a56567d1d4df733e7/drivers/overlay/overlay.go#L1503-L1506

It seems that `permsKnown` already needs to be true, because otherwise the for loop would have been skipped.

Here is the relevant code:

https://github.com/containers/storage/blob/2431799327396be3322f440a56567d1d4df733e7/drivers/overlay/overlay.go#L1495-L1507

The code originates from the PR
 * https://github.com/containers/storage/pull/772

**Comment by rhatdan** [comment]
@giuseppe @mtrmac PTAL

**Comment by giuseppe** [comment]
@eriksjolund you are right.

Opened a PR:

- https://github.com/containers/storage/pull/1934
