### ISSUE TITLE
composefs: committing the finished image: failed to put layer using a partial pull: rename xxx/diff: no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/storage#1915]
The gist seems to be:
```
# podman-remote [something that does a pull]
Error: committing the finished image: \
    failed to put layer using a partial pull: \
    rename /var/lib/containers/storage/overlay/staging/1464572085 \
        /var/lib/containers/storage/overlay/SHA/diff: \
    no such file or directory
```
Seems to be remote-only.

Been trying all afternoon to reproduce this. I can't. So here are links to failure logs:
* [f39](https://api.cirrus-ci.com/v1/artifact/task/4751426792980480/html/sys-remote-fedora-39-root-host-sqlite.log.html), in `podman load from URL` test
* [rawhide](https://api.cirrus-ci.com/v1/artifact/task/5314376746401792/html/sys-remote-rawhide-root-host-sqlite.log.html), ibid
* [f39 aarch64](https://api.cirrus-ci.com/v1/artifact/task/5032901769691136/html/sys-remote-fedora-39-aarch64-root-host-sqlite.log.html), in `pod something infra something` test

**Comment by giuseppe** [comment]
we should not be so aggressive to cleanup the staging directory: https://github.com/containers/storage/blob/3cbd3c6fcd26cc961c1b462575aa1f0c597a24b1/drivers/overlay/overlay.go#L883

I am not sure yet how to address it, I'll keep working on this

**Comment by giuseppe** [comment]
opened a PR
