### ISSUE TITLE
Provide contacting information in README.md

### ISSUE THREAD

**Issue by Silvanoc** [containers/storage#193]
I'm looking for the best way to get in contact with this community and I cannot find that information anywhere in the project. I think it would be meaningful having this information available in the README.md.

Of course, I could just create an issue, but I'm not sure if it's the expected behavior also for generic questions. Even it that's the expected behavior, having that information in the README.md would be helpful for newcomers, like me :smile:

**Comment by Silvanoc** [comment]
BTW, the same applies to containers/image.

**Comment by rhatdan** [comment]
CONTRIBUTING.md provides some of this information. Perhaps we should link the README.md to this file to make it clearer.

**Comment by Silvanoc** [comment]
I should have found it myself :fearful:

**Comment by Silvanoc** [comment]
@rhatdan thank you for the quick reaction! :+1:

**Comment by rhatdan** [comment]
No Problem.  Welcome, and hopefully you will contribute to some of our projects.
