### ISSUE TITLE
SELinux: Mount image using different contexts

### ISSUE THREAD

**Issue by saschagrunert** [containers/storage#1994]
The OCI Volume Source Kubernetes enhancement (https://kep.k8s.io/4639) will require CRI-O to mount images on container creation. The pull itself will not change from a runtime perspective, but we need to use the existing `MountImage` API to create an OCI mount from the host path to the workload destination.

https://github.com/containers/storage/blob/52b643e1ff51ae0a05693adf8fae5a134b32b478/store.go#L259-L262

The API supports passing a `mountLabel`, but multiple containers could request the same image mount using different labels.

Would it make sense to extend the API to have a unique mount path per SELinux context?

cc @mrunalp @haircommander

**Comment by giuseppe** [comment]
the file system will be mounted read-only, so it is not possible to overwrite the files in the image given the image mountpoint itself.

Is there any downside to just mount the image with a permissive label so that it can be used by multiple pods without issues?

Another alternative that you could investigate is to use an overlay mount inside the OCI config file itself and use the image mount as a lower layer:

1. mount the image
2. use an overlay mount inside the OCI configuration where the lower layer is the image mount point, and specify the label you want

An advantage of this solution is that the mount won't propagate to the host, since it will happen inside the container mount namespace

**Comment by saschagrunert** [comment]
Thank you for the response @giuseppe! I'll check if we can even run into the mentioned issue with OpenShift to avoid fixing something we cannot run into.

> 1. mount the image

Using the `MountImage` API and an empty `mountLabel`?

> 2. use an overlay mount inside the OCI configuration where the lower layer is the image mount point, and specify the label you want

Like
```json
{
        "type": "overlay",
        "source": "overlay",
        "options": [
            "workdir=...",
            "upperdir=...",
            "lowerdir=/var/lib/containers/storage/overlay/$ID/merged"
        ]
    },
```

where workdir and upperdir would be chosen by the runtime outside of c/storage?

**Comment by giuseppe** [comment]
> Like
> 
> ```json
> {
>   "type": "overlay",
>   "source": "overlay",
>   "options": [
>     "workdir=...",
>     "upperdir=...",
>     "lowerdir=/var/lib/containers/storage/overlay/$ID/merged"
>   ]
> }
> ```

I'd use something like:

```json
{
  "type": "overlay",
  "source": "overlay",
  "options": [
    "lowerdir=/var/lib/containers/storage/overlay/$ID/merged:/var/run/crio/emptydir"
  ]
}
```

you can reuse the emptydir with multiple mounts, and the mount is read-only since overlay won't allow any write without an upperdir

**Comment by saschagrunert** [comment]
I have something working in https://github.com/cri-o/cri-o/pull/8317/commits/cb1fcd8aa7612c1d1281dc1fcf55b43f84fe2547#diff-1e0877112035840d3e2f073c693665f8daffa241a440e54a866ad7382b510ea2R1236-R1285

I assume that `specgen.SetLinuxMountLabel(mountLabel)` is enough to apply the right label: https://github.com/cri-o/cri-o/blob/cb1fcd8aa7612c1d1281dc1fcf55b43f84fe2547/server/container_create_linux.go#L812

**Comment by saschagrunert** [comment]
But we may not need this at all, if we mount the first volume it will be mounted with the first pods selinux label. If we need it for a different one, we can relabel it. Existing volumes don't have multiple labels at once.
