### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by nalind** [containers/storage#2]
Defaults are nice and all, but we probably need a configuration file that we can consult by default to fill in missing information when a calling application doesn't want to care about locations or which driver to use.

A first guess is a TOML file with each section containing a tuple of the startup parameters (root directory, runtime root, driver name, driver options) that it will match against if some of the parameters aren't specified, so that it could fill in the blanks if it was given only the first of those, and we could hard-code a default for just that one value.

This would make it much easier for external code to dictate the settings for a given storage location, since we're not all that interested in setting that policy here, either.

**Comment by rhatdan** [comment]
Should this belong to container/storage or OCID?
@mrunalp @runcom PTAL

**Comment by mrunalp** [comment]
I think that since this is a library, it makes sense to have the config in OCID. The config paramaters could be passed to the storage library instantiation code.

**Comment by nalind** [comment]
I'd lean that way as well, but I opened the issue so that we could try to figure out how that's supposed to work when OCID's not the only logic that might want to be poking at the layer storage.  Expecting them to parse OCID's configuration file to get this information would feel a bit odd.

**Comment by rhatdan** [comment]
Yes that true, but wouldn't the other tool have similar config? 
Lets look at a system like
atomic CLI and ocid
If an admin wanted atomic and OCID to share the same storage, I would think they would need to configure both.  That way we would have flexibility for each tool to have separate storage.

**Comment by mrunalp** [comment]
Applications utilizing containers/storage will differ in what file format they want to use (toml, yaml, json, etc). We could just provide an API that takes in a config struct and leave it up to the application to populate the config struct which should be relatively simple glue code using the appropriate parsing library for the format they use. 

```go
type StorageConfig struct {
     type string,
     rootDir string,
     ...
}

func parseConfig(path string) (*StorageConfig, error) {
...
}

err, config := parseConfig("/path/to/config") // parseConfig could be left to the application
st := storage.New(config) // This API could be in containers/storage
```

**Comment by nalind** [comment]
I'd be wary that this would lead to requiring the same information to be written to multiple places by something like docker-storage-setup, in order to get OCID and, for example, skopeo on the same page, but it's not a deal-breaker.

The current MakeStore() function accepts its configuration as multiple arguments, but passing in a single structure that can have fields added, and I suppose tagged to make encoding/decoding easier, is probably better because it would survive things like the addition of UID and GID maps without requiring

**Comment by rhatdan** [comment]
I agree lets more to a structure passing and leave the configuration tool to something else.  We are going to have to figure out what we can do with @rhvgoyal docker-storage-setup.

**Comment by nalind** [comment]
Okay, moved to have the initialization function take a structure, to hopefully require fewer changes in consumers of the library if/when new settings are added.
