### ISSUE TITLE
Report unsupported configuration options

### ISSUE THREAD

**Issue by Silvanoc** [containers/storage#203]
Providing the option `ostree_repo` in a section where it's not supported (`[storage.options.thinpool]`) is being silently ignored without reporting neither a warning nor an error.

See issue #196 for an example.

**Comment by rhatdan** [comment]
@Silvanoc Is this still and issue?

**Comment by Silvanoc** [comment]
I'd have to test it, I don't have a current version of c/storage now available. I can have a look at it over the weekend.

If you have one, it's as easy as adding a valid, but not supported configuration to `storage.conf` and seeing what happens when starting libpod/buildah/skopeo... For example:
```
[storage]
pure_nonsense = ""
```

**Comment by rhatdan** [comment]
In that case you want an error or warning message?

**Comment by Silvanoc** [comment]
I think that an error would be the most meaningful thing to do, but it would difficult the possibility of adding custom extensions.

In the end I don't have a strong opinion about either error or warning.

**Comment by rhatdan** [comment]
I don't see a way to do this with toml library we are using, so closing.  I think we would have to move to a different library and no one is willing to go through the effort.
