### ISSUE TITLE
composefs?? random ENOENTS in CI

### ISSUE THREAD

**Issue by edsantiago** [containers/storage#2033]
Seeing a lot of these in my no-flake-retry PR, only on rawhide root, only today:
```
something something
Error: copying layers and metadata for container "cid":  \
    initializing source containers-storage:test1: \
    extracting layer "sha": \
    lgetxattr /tmp/CI_RQPB/podman-e2e-827543605/imagecachedir/overlay/sha/merged/usr/bin/killall: no such file or directory
```
or
```
Error: exporting root file-system diff for "sha": \
    lgetxattr /tmp/CI_RQPB/podman-e2e-827543605/imagecachedir/overlay/sha/merged/usr/bin/bunzip2: no such file or directory
```
or `llistxattr` or even just `open`. There's also a very weird one in [podman diff](https://api.cirrus-ci.com/v1/artifact/task/4848537404440576/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-diff-podman-diff-latest-container--1) that does not match the same pattern but I would bet is related.

Today's changes are (1) local registry and (2) test composefs on rawhide.

* rawhide : int podman rawhide root host sqlite
    * [07-11 09:14](https://api.cirrus-ci.com/v1/artifact/task/4848537404440576/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-commit-podman-commit-with-volumes-mounts-and-no-include-volumes--1) in Podman commit podman commit with volumes mounts and no include-volumes
    * [07-11 09:14](https://api.cirrus-ci.com/v1/artifact/task/4848537404440576/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-pod-create-podman-create-pod-with-infra-image--1) in Podman pod create podman create pod with --infra-image
    * [07-11 09:14](https://api.cirrus-ci.com/v1/artifact/task/4848537404440576/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-checkpoint-podman-restore-multiple-containers-from-single-checkpoint-image--1) in Podman checkpoint podman restore multiple containers from single checkpoint image
* rawhide : int remote rawhide root host sqlite [remote]
    * [07-11 09:14](https://api.cirrus-ci.com/v1/artifact/task/4707799916085248/html/int-remote-rawhide-root-host-sqlite.log.html#t--Podman-run-entrypoint-podman-run-user-entrypoint-with-command-overrides-image-entrypoint-and-image-cmd--1) in Podman run entrypoint podman run user entrypoint with command overrides image entrypoint and image cmd

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(4) | podman(3) | rawhide(4) | root(4) | host(4) | sqlite(4) |
|  | remote(1) |  |  |  |  |

**Comment by giuseppe** [comment]
potential fix: https://github.com/containers/storage/pull/2036, I am still validating it

I'll update here when it is ready for testing/review
