### ISSUE TITLE
Support symlinks to devices

### ISSUE THREAD

**Issue by bhperry** [containers/storage#207]
Feature request:

Resulting from this issue I posted on CRI-O: https://github.com/kubernetes-incubator/cri-o/issues/1727

It would be really nice if `checkDevAvailable` in https://github.com/containers/storage/blob/932e49f1debc6fbc0e3e8d96f83bdc7d496a0909/drivers/devmapper/device_setup.go could evaluate symlinks. Since nvme device ordering is not guaranteed and I'm already doing the work to match up nvme -> xvd_, it would be really nice if I could use those symlinks for CRI-O's `directlvm_device`.

**Comment by rhatdan** [comment]
@nalind Do you think this is a good idea.

**Comment by rhatdan** [comment]
@bhperry Still interested in this/  Do we have it now?  Can I close this?

**Comment by bhperry** [comment]
Still haven't gotten around to testing, but looks like the linked MR covers it. I'd say we're good to close this.
