### ISSUE TITLE
Improve documentation of containers-storage.conf(5)

### ISSUE THREAD

**Issue by vrothberg** [containers/storage#209]
I started working on improving the CRI-O docs (see https://github.com/kubernetes-incubator/cri-o/issues/1747) and am about to reference `containers-storage.conf(5)` to avoid redundancy among manpages and to have a reference for details about all storage drivers and options.

I think that the `containers-storage.conf(5)` should be improved to reflect the current state of `containers/storage`. I am also missing a list of supported drivers with some explanation. Maybe other aspects need to be completed as well? I only have limited knowledge about `containers/storage` and don't consider myself to be a good candidate working on this issue.

**Comment by vrothberg** [comment]
The manpage also states to be `storage.conf(5)` which might be a relict from the past.

**Comment by rhatdan** [comment]
mounts.conf is realy related to the secrets patch so it should go into libpod.

**Comment by rhatdan** [comment]
Right we package up these man pages inside of containers-common.  But gather them from containers/image and containers/storage.

**Comment by rhatdan** [comment]
Well we don't install those man pages and don't really support that executable.  I believe that executable is just for testing.

**Comment by vrothberg** [comment]
That's not what the manpage states :( If that's the case, I'll remove that from our packages asap.

**Comment by rhatdan** [comment]
We don't even ship a container-storage package.

**Comment by vrothberg** [comment]
We do, mostly because of the `storage` binary. We have a libcontainers-{common,image,storage} but I am more and more convinced that everything can go into libcontainers-common.

**Comment by rhatdan** [comment]
Yup.

**Comment by rhatdan** [comment]
Closing this because we have updated containers-storage man page and continue to.
