### ISSUE TITLE
Fix `d.getStagingDir("")`

### ISSUE THREAD

**Issue by mtrmac** [containers/storage#2092]
Since #1784 , https://github.com/containers/storage/blob/10981abafe3e3ece4e0cc872761f7624cd1bef0e/drivers/overlay/overlay.go#L2188 is calling `getStagingDir("")`, i.e. `dir2` with a layer ID `""`.

Just from reading the code, that _happens_ to work as expected because it is not using the primary return value of `dir2`, but that’s extremely non-obvious and very likely to be broken during future maintenance. To the extent the cod is only looking for the “homeDir”, I think that should be modeled explicitly and not use the `id` value at all. Alternatively, if the `id` value mattered, then this needs to actually be implemented.

Cc: @giuseppe

**Comment by giuseppe** [comment]
opened https://github.com/containers/storage/pull/2107
