### ISSUE TITLE
copy.DirCopy fails when encountering sockets

### ISSUE THREAD

**Issue by anderbubble** [containers/storage#2113]
[We](https://github.com/warewulf/warewulf) use `copy.DirCopy` and have encountered a behavior that, if the source contains sockets, the copy operation fails with an error of the form:

```
lchown /var/lib/warewulf/chroots/gpuslurm/rootfs/run/user/0/gnupg/d.kg8ijih5tq41ixoeag4p1qup/S.gpg-agent: no such file or directory
```

Could `copy.DirCopy` be updated to ignore sockets in the source in stead?

Reported for Warewulf at https://github.com/warewulf/warewulf/issues/892

**Comment by giuseppe** [comment]
yes, I think we should skip sockets.  Would you like to open a PR?

**Comment by anderbubble** [comment]
> yes, I think we should skip sockets. Would you like to open a PR?

I'll have a look; thanks!

**Comment by anderbubble** [comment]
@giuseppe PR submitted. Thanks for the support! Let me know if there's anything else you need from me, particularly to get it backported to a release that supports go 1.21 or earlier.
