### ISSUE TITLE
Make Images aware of repos and tags

### ISSUE THREAD

**Issue by vrothberg** [containers/storage#218]
containers/storage identifies images by names (strings). This allows fast lookups but it breaks compatibility with Docker.

For instance, when pulling a newer image via `podman-pull` or when over-tagging an image via `podman-tag`, the repository and the tag of the image will be lost and reported as ```<none> <none>```. Docker will only remove the tag but keep the repository data (e..g, `alpine <none>`).

@nalind and I discussed to keep the storage API as is but to find a way to make it a bit smarter under the hood, for instance, by decomposing the image-string as [libpod does](https://github.com/containers/libpod/blob/master/libpod/image/parts.go#L26).

Cc: @baude @mheon @rhatdan @TomSweeneyRedHat

**Comment by mheon** [comment]
I'll add @mtrmac to this one as well, considering his work on images and c/image.

**Comment by mtrmac** [comment]
I’m not quite sure what the benefit of (`alpine` repo, unknown details) is — but there is definitely a problem in that images store a single “manifest digest” value, whereas a single image object may be pulled from many different repositories and many different repo@digest values; we need to store all of them, and be able to look up by all of them. Assuming that, (repo, manifest digest) is a superset of the desired (repo, unknown details) information.

**Comment by vrothberg** [comment]
> I’m not quite sure what the benefit of (alpine repo, unknown details) is [...]

Docker compatibility. I assume that the reasoning behind was to keep repo as only the tag needs to be overwritten. Personally, I find it a bit more user-friendly.

> [...] but there is definitely a problem in that images store a single “manifest digest” value, whereas a single image object may be pulled from many different repositories and many different repo@digest values [...]  Assuming that, (repo, manifest digest) is a superset of the desired (repo, unknown details) information.

@nlind, is @mtrmac's assumption correct?

**Comment by vrothberg** [comment]
Ping @nalind

**Comment by vrothberg** [comment]
Closing as it does not seem relevant anymore.
