### ISSUE TITLE
improve "open /etc/subuid: no such file or directory" error message

### ISSUE THREAD

**Issue by vrothberg** [containers/storage#231]
Existing openSUSE deployments will run into the issue that /etc/sub{g,u}id are not present as no (base) package added those; useradd and usermod don't create those files. I've fixed this via the shadow package now adding those files so that new installs and new users have proper entries but that doesn't solve the issue for existing users.

In other words, existing users don't have this file and will always run into Podman failing with "open /etc/subuid: no such file or directory". I think Podman should catch those errors and guide the user a bit more, maybe even printing the corresponding section from podman (1).

Tracking-bug for https://github.com/containers/libpod/issues/1755

**Comment by rhatdan** [comment]
Since the libpod patch was merged, I am closing this PR.
