### ISSUE TITLE
devmapper regression

### ISSUE THREAD

**Issue by runcom** [containers/storage#233]
See https://github.com/kubernetes-sigs/cri-o/issues/1883 for more information, the range of commits which probably broke devmapper in CRI-O is:

```
# this is the range changed with https://github.com/kubernetes-sigs/cri-o/pull/1814 wihch broke devmapper
git log --oneline --ancestry-path 88d80428f9b146f8f9fe7e2e8cc8688a5aae1a4e..68332c059156eae970a03245cfcd4d717fb66ecd
```

68332c059 Merge pull request #216 from giuseppe/userns-restore-setuid-setgid
2df72f37c chown: restore SUID and SGID bits
1d49427fe Merge pull request #215 from nalind/create-error
2805a4374 layerStore.Put(): always check for Create() errors
02db7cbb0 Merge pull request #214 from nalind/hold-locks
3df3c9f9a Hold the layer store lock while diffing
243c4cd61 Merge pull request #213 from nalind/rolayer-lock
c8670efc1 Fix a lock inversion
d0cb01076 Merge pull request #212 from zmedico/locker-locked-stub-to-lockfile_windows
587b6cc0f Implement Locker.Locked() for windows
9fcbb57eb Merge pull request #210 from zmedico/lock-sanity-checks-for-save-methods
c7ba5749d Add lock sanity checks to Save() methods
17c7d1fee Merge pull request #205 from rhatdan/subuid
ad12a7039 Add more information in errors about missing uidimappings or gidmappings
956a19716 Merge pull request #195 from giuseppe/fuse-overlayfs-shifting
3f55e5a3a shifting: raise an error if the container needs shifting
06cea37b8 tests: add test for shifting support
189739633 drivers: inform Mount of the mappings used by the container
140e0b60e Makefile: install ffjson
883ee15e4 store: use the original image if the driver supports shifting
1e60d8a4c store: include layerID in the error message
9bb1031ef drivers: add new method SupportsShifting() to LayerIDMapUpdater
648024562 overlay: enable support for shifting when FUSE is used
8c814e007 overlay: use full paths to the mount program
9f0144d96 storage.conf: move ostree_repo and skip_mount_home to the correct section
afdedba2d Merge pull request #201 from rhatdan/mountopt
2569af9a0 Fix overlay to handle mountopt properly
7098fdce9 Merge pull request #176 from rhatdan/mount-options
8b1a0f8d6 Add default mount options to pass to drivers
cb8d712f7 Merge pull request #200 from rhatdan/mounted
153897188 Change Mounted to return the number of times mounted
46a8a1cdd Merge pull request #198 from rhatdan/umount
1075a73ca Modify storage to allow callers to determine if a mount point is mounted
124de6810 Merge pull request #199 from giuseppe/allow-to-override-conf-file
e933db596 storage: rename fuse_program to mount_program
759aab13f storage: allow to override .fuse_program from the conf file
c4aa7ad98 store: move configuration file parsing to new function
0ab754169 Merge pull request #197 from TomasTomecek/master
404315aae log errors from ApplyUncompressedLayer
90d0a58ff Merge pull request #194 from rhatdan/contributing
3a5d1ec34 Potential contributors need to find the CONTRIBUTOR information.
9cbb6cb3f Merge pull request #137 from giuseppe/ostree-storage
13af8ce95 tests: add test for ostree deduplication
d33931a3e tests: set mtime to the epoch
c7fdad430 ci: install ostree
85bf5a4b8 Vagrantfile: update to Fedora 28
6c122a294 vagrant: install ostree
f3e7ee3c2 configuration: new option skip_mount_home
52a37816a vfs: add support for ostree deduplication
0c7cb6041 overlay: new option to support ostree deduplication
ffd808a47 ostree: new package
eca8a1792 storage: add ostree files
58f557cf1 Merge pull request #191 from giuseppe/overlay-fuse-program
fc4b8629c containers-storage: add new option .fuse_program
51f1f85c2 Merge pull request #190 from marcov/better-failmsg
d990e2b32 Improve duplicate name error message on container create

**Comment by rhatdan** [comment]
How quickly can kata recreate the issue?  Can we start bisecting these to figure out exactly what PR broke Kata?  

What is the exact symptom that kata is failing on ?

**Comment by runcom** [comment]
> How quickly can kata recreate the issue? Can we start bisecting these to figure out exactly what PR broke Kata?

I've asked them to do so and they're on it last time we spoke



> What is the exact symptom that kata is failing on ?

It's an invalid argument thrown when unmounting the devmapper mount

**Comment by rhatdan** [comment]
The only argument we ever give to unmount under devicemapper is MNT_DETATCH.
```
	if err := unix.Unmount(mountPath, unix.MNT_DETACH); err != nil {
		return err
	}
```
@rhvgoyal Could yo ulook in the kernel when does unmount return EINVAL?

**Comment by runcom** [comment]
@chavafg @sboeuf this issue is tracking the regression from https://github.com/kubernetes-sigs/cri-o/issues/1883
Could you assist Dan?

**Comment by qiancai** [comment]
> > How quickly can kata recreate the issue? Can we start bisecting these to figure out exactly what PR broke Kata?
> 
> I've asked them to do so and they're on it last time we spoke
> 
> > What is the exact symptom that kata is failing on ?
> 
> It's an invalid argument thrown when unmounting the devmapper mount

Looks like same issues can be reproduced by podman then.
https://bugzilla.redhat.com/show_bug.cgi?id=1623944
https://bugzilla.redhat.com/show_bug.cgi?id=1625394

**Comment by chavafg** [comment]
Hi
This can be reproduced very quickly, you just need to setup devicemapper for cri-o and then create and remove a pod.

I use this storage config on `/etc/crio/crio.conf`:
```
# Storage driver used to manage the storage of images and containers. Please
# refer to containers-storage.conf(5) to see all available storage drivers.
storage_driver = "devicemapper"

# List to pass options to the storage driver. Please refer to
# containers-storage.conf(5) to see all available storage options.
storage_option = [
        "dm.directlvm_device=/dev/sdb",
        "dm.directlvm_device_force=true",
        "dm.thinp_percent=95",
        "dm.thinp_metapercent=1",
        "dm.thinp_autoextend_threshold=80",
        "dm.thinp_autoextend_percent=20"
]
```

And then use these steps:
```
$ sudo crictl runp "$TESTDATA"/sandbox_config.json
$ sudo crictl stopp <pod_id>
$ sudo crictl rmp <pod_id>
```

I'll try to check which of the commits here is the one that broke devicemapper.

**Comment by chavafg** [comment]
So I revendored `github.com/containers/storage` to commit `124de6810ea8ab6b69e382af281eff2c214bf3e2`  in cri-o and everything worked correctly. 
The next change is `46a8a1cddbd8486f12bbebc9ffcdd7f65e81b48f` from #198 and using this commit the issue can be reproduced.

BTW, I could also use podman to reproduce the issue:
```
fuentess@crio-dm:~/go/src/github.com/containers/libpod$ sudo podman run -dt -e HTTPD_VAR_RUN=/var/run/httpd -e HTTPD_MAIN_CONF_D_PATH=/etc/httpd/conf.d                   -e HTTPD_MAIN_CONF_PATH=/etc/httpd/conf
                 -e HTTPD_CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/httpd/                   registry.fedoraproject.org/f27/httpd /usr/bin/run-httpd
ERRO[0000] File descriptor 6 (/dev/mapper/control) leaked on pvdisplay invocation. Parent PID 3619: podman
  Failed to find physical volume "/dev/sdb".
  error="exit status 5"
Trying to pull registry.fedoraproject.org/f27/httpd...Getting image source signatures
Copying blob sha256:ff3dab903f926d26db009e0dcd575b8ccea7635b6b225835c35df765662707ec
 80.73 MB / 80.73 MB [=====================================================] 27s
Copying blob sha256:9347d6e9d8644ec22930b7dd78ba0cfcab8fd9a09d57545d4d74649ca929df0c
 7.30 MB / 7.30 MB [========================================================] 0s
Copying blob sha256:2fc5c44251d42d4e8bdc547a79e7ad1efffdf11f74ceea6a83e2fb6743aeff7d
 44.82 MB / 44.82 MB [=====================================================] 14s
Copying config sha256:18f01f6f77ef941f5b31dd007d113620cbb1939ac33d1922edce7d9d2c9ebad7
 6.55 KB / 6.55 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
3128d42ada831a56614c35dceefbddacf1128d6101e3a62b9b0dd974bb3c1a9e
fuentess@crio-dm:~/go/src/github.com/containers/libpod$ sudo podman ps
CONTAINER ID  IMAGE                                        COMMAND               CREATED         STATUS             PORTS  NAMES
3128d42ada83  registry.fedoraproject.org/f27/httpd:latest  container-entrypo...  26 seconds ago  Up 24 seconds ago         loving_volhard
fuentess@crio-dm:~/go/src/github.com/containers/libpod$ sudo podman stop 3128d42ada83
3128d42ada831a56614c35dceefbddacf1128d6101e3a62b9b0dd974bb3c1a9e
fuentess@crio-dm:~/go/src/github.com/containers/libpod$ sudo podman rm 3128d42ada83
ERRO[0000] devmapper: Error unmounting device 12dad3ad01aa2823cce01e78e35ef02ba6745bb850cbd46c978c3438873bffaa: invalid argument
error removing container 3128d42ada831a56614c35dceefbddacf1128d6101e3a62b9b0dd974bb3c1a9e root filesystem: invalid argument
```

I used this storage configuration for podman:
```
fuentess@crio-dm:~/go/src/github.com/containers/libpod$ cat /etc/containers/storage.conf
[storage]
driver = "devicemapper"


[storage.options]

[storage.options.thinpool]

directlvm_device="/dev/sdb"
directlvm_device_force="True"
thinp_percent=95
thinp_metapercent=1
thinp_autoextend_threshold=80
thinp_autoextend_percent=20
```

**Comment by runcom** [comment]
> So I revendored `github.com/containers/storage` to commit `124de6810ea8ab6b69e382af281eff2c214bf3e2` in cri-o and everything worked correctly.
> The next change is `46a8a1cddbd8486f12bbebc9ffcdd7f65e81b48f` from #198 and using this commit the issue can be reproduced.

so, reverting #198 altogether fixes your issue?

**Comment by runcom** [comment]
This the only suspicious line I've found in #198 which is still unmounting w/o force (so leaving mounts behind) https://github.com/containers/storage/pull/198/files#diff-a281f22627802db5c62d316f5eac7a96R932

**Comment by sboeuf** [comment]
@runcom which line? The link you provided does not specify any particular line or range.
I'm asking to make sure we're on the same page, and potentially @chavafg could confirm if this is the culprit.

**Comment by runcom** [comment]
Here it is https://github.com/rhatdan/storage/blob/1075a73cac3054422c5cda2712ec5412eedce573/layers.go#L932

I doubt that can be the issue but it's the only place I see `Unmount(..., false)` and if you guys can reproduce, the better. I'll take another look at #198 to spot some flaw which could lead to this, always assuming #198 is the culprit.

@sboeuf @chavafg  could you guys try reverting that PR altogether to actually narrow down if that's the real issue?

**Comment by sboeuf** [comment]
@runcom 
>I doubt that can be the issue but it's the only place I see Unmount(..., false) and if you guys can reproduce, the better.

Yes of course. @chavafg could you please try to set this line to `_, err := s.r.Unmount(s.id, true)`, recompile, and see if you can still reproduce?

>@sboeuf @chavafg could you guys try reverting that PR altogether to actually narrow down if that's the real issue?

I don't follow, @chavafg already confirmed that this PR was the problem. He did bisect and found that it was the one causing the failure.

**Comment by runcom** [comment]
alright I may have found the issue, I'm running kata ci in crio to see if that's the issue, I'll open a PR here if that fixes the issue for Kata (https://github.com/kubernetes-sigs/cri-o/pull/1910)

**Comment by runcom** [comment]
see https://github.com/containers/storage/pull/240 and https://github.com/kubernetes-sigs/cri-o/pull/1910 which are fixing this

**Comment by runcom** [comment]
actually there seems to be yet another issue on top of my fixes:
```
# time="2018-11-15 10:49:20.990108059Z" level=debug msg="devmapper: Shutdown lookup device mnt, error: devmapper: Unknown device mnt" 
```
