### ISSUE TITLE
Scope mounting options (with build tags)

### ISSUE THREAD

**Issue by erikh** [containers/storage#28]
Currently I cannot build a static binary because of the devmapper requirement. My application will never use devicemapper in practice and probably not several of the other options. I would like the ability to filter them.

I can provide the patch for this, just need the go-ahead.

**Comment by rhatdan** [comment]
I am fine with adding filters to eliminate unsupported backends.

**Comment by rhatdan** [comment]
@erikh Are you still interested in this?
