### ISSUE TITLE
Possible integer overflow for IDMap parsing on 32bit systems

### ISSUE THREAD

**Issue by saschagrunert** [containers/storage#316]
Hey, I'm not sure if 32bit support is a thing for `containers/storage` so feel free to close if out of scope.

The function `ParseIDMap()` parses the G/UID triple and then cast the `uint32` results to `int`:
https://github.com/containers/storage/blob/ed97cd56f06fb41597db9f76f09b3105e52ed53a/pkg/idtools/parser.go#L47-L51

I tested the parser with a 32bit build and got a wrong result because `int` is not large enough:

```go
func main() {
	m, _ := ParseIDMap([]string{"1:4294967285:0"}, "GID")
	fmt.Printf("%v\n", m)
}
```
```
> export GOARCH=386
> go run parser.go
[{1 -11 0}]
```

I fix would break APIs so I would like to ask you which way we want to go here. :)

**Comment by rhatdan** [comment]
We want to support 32 bit arches with containers/storage.
@saschagrunert @giuseppe @nalind How would you suggest we fix this?

**Comment by saschagrunert** [comment]
> We want to support 32 bit arches with containers/storage.
> @saschagrunert @giuseppe @nalind How would you suggest we fix this?

I would let the API stable and add an additional overflow check before casting.

**Comment by rhatdan** [comment]
@saschagrunert Could you open a PR?
