### ISSUE TITLE
Documentation for usage of OSTree deduplication missing

### ISSUE THREAD

**Issue by Silvanoc** [containers/storage#323]
Thanks to [this comment in a test](https://github.com/containers/storage/blob/2f12336bf40037fd5c9b8aa2c50e362b7858bf83/tests/import-layer-ostree.bats#L40) I've discovered that the OSTree deduplication only applies to read-only layers.

The manpages of `container-storage` don't report any command or option to make use of it, but the option exists for commands [`create-layer`](https://github.com/containers/storage/blob/3d342550da009a8035d663b7aa38d01b4b2ff8bf/cmd/containers-storage/create.go#L221) and [`import-layer`](https://github.com/containers/storage/blob/3d342550da009a8035d663b7aa38d01b4b2ff8bf/cmd/containers-storage/create.go#L241).

On my experiments I couldn't find out how to get OSTree deduplication using `create-layer --readonly`.
With `import-layer --readonly` works as expected and tested by `import-layer-ostree.bats`.

---
Out of the previously mentioned issues I'd say that following tasks would be meaningful:

- [x] Document in the manpage of `containers-storage` that a read-only layers are needed to get OSTree deduplication.
- [ ] Update manpage of `create-layer`. At least the option `--readonly, -r` is missing.
- [x] Add a manpage for `import-layer`.
- [ ] Document how to create a read-only layer by using `create-layer`, or otherwise what's the consequence of `create-layer --readonly`.

**Comment by Silvanoc** [comment]
I might help on the first three tasks, but not on the fourth until someone explains me how it's supposed to be used.

**Comment by Silvanoc** [comment]
The current [last commit](https://github.com/containers/storage/commit/3da0b926c7ba5eca0f7144760e4f9fca8a2100be) from @rhatdan catch my attention, since it's also about non-writable storage.

Having a look at the tests, I'm puzzled since I cannot see in [`tests/store.bats`](https://github.com/containers/storage/blob/3da0b926c7ba5eca0f7144760e4f9fca8a2100be/tests/stores.bats) what makes `ro-root` become a read-only storage... Is it the [`shutdown`](https://github.com/containers/storage/blob/593f2796eb3b93c6312fc0d70295ea796fa3b601/tests/stores.bats#L60)?

In general, does it have anything to do with read-only layers? Or is it something completely different?

**Comment by rhatdan** [comment]
They are just additional stores, and we are not really making them read-only.  They just would never be written to containers-storage.  My goal is to allow us to build a container images owning buildah that can be run in a container and share the container-storage on the host, but write to a separate location.

This PR Shows how the buildahctr will be built.

https://github.com/containers/buildah/pull/1540

Then I would run it with this command.

podman run -ti --device=/dev/fuse -v ${PWD}/Dockerfile:/root/Dockerfile:z,ro -v /var/lib/containers/storage:/var/lib/shared:ro -v /var/lib/mycontainers/:/var/lib/containers:Z buildahctr buildah bud --no-cache /root

Notice I mount /var/lib/containers/storage as /var/lib/shared as read-only.  Then I configure storage.conf to use the additonalimages from /var/lib/shared inside of the container.  This allows those lower level images on the host to be used by the new layers in the container, and the buildahctr does not have to pull those images.

**Comment by Silvanoc** [comment]
@rhatdan thanks for the quick answer!

Pretty much what I had supposed, but it's good to have the confirmation. So it doesn't have anything to do with this issue.

**Comment by rhatdan** [comment]
@Silvanoc Please open PRs to fix the first couple.  I will leave it up to @nalind TO answer the last one.

**Comment by Silvanoc** [comment]
@rhatdan do you mean with couple two or three?

WRT the 2nd one, I wouldn't document `create-layer --readonly` until having clarified the 4th one. I still see the possibility that option `--readonly` doesn't have any impact on `create-layer`...

**Comment by rhatdan** [comment]
@Silvanoc Do you still need this?  Is this something that we have done to you satisfaction?  @giuseppe @nalind WDYT?

**Comment by Silvanoc** [comment]
As mentioned in [this comment](https://github.com/containers/storage/issues/331#issuecomment-549262794) to issue #331, I'm not pursuing the OSTree path for deduplication anymore.

We will have to rely on filesystem-deduplication (e.g. BTRFS) or the poorer layer deduplication on edge/embedded devices...

Should I close it?

**Comment by rhatdan** [comment]
I will.
