### ISSUE TITLE
overlay storage driver doesn't support Windows Subsystem for Linux's lxfs

### ISSUE THREAD

**Issue by sunnychanwork** [containers/storage#327]
see https://github.com/containers/libpod/issues/3000

The storage driver was trying to mount overlay on WSL's lxfs but it was unable to do so:

```
DEBU[0000] overlay test mount with multiple lowers failed mountfrom re-exec error: exit status 1: output: invalid argument
DEBU[0000] overlay test mount with a single lower failed mountfrom re-exec error: exit status 1: output: invalid argument
```

Notice that overlay fs does work under WSL:

```

root@HOST:~# uname -a
Linux HOST 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
root@HOST:~# mount -t overlay -o lowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/workdir none /tmp/overlay
root@HOST:~# mount | grep /tmp/overlay
none on /tmp/overlay type overlay (rw,relatime,lowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/workdir)
```

**Comment by rhatdan** [comment]
@nalind Any ideas? Are we adding additional arguments to the tests?

**Comment by nalind** [comment]
When we fell through to the single-lower test, which lets us be discern whether the multi-lower test failed due to a lack of multi-lower support and not just a general overlay-not-working-on-the-lower-fs error, we were attempting the single-lower test incorrectly.  #328 corrects it.

**Comment by nalind** [comment]
This suggests that the WSL overlay filesystem doesn't support using multiple lower directories for a single mount.

**Comment by rhatdan** [comment]
Well at least it does not if you don't specify an upper directory.

**Comment by rhatdan** [comment]
Looks like we had a bug anyways.
