### ISSUE TITLE
OSTree doesn't deduplicate and breaks deduplication

### ISSUE THREAD

**Issue by Silvanoc** [containers/storage#331]
I was expecting OSTree to be used for file deduplication in the layers, when configured. But it's not working properly (or I have fully wrong expectations).

My expectation was that the files in the `diff` of a readonly layer are a `checkout` of the OSTree repository (becoming hard-links to it). But it isn't so, they are just **copies** of it.

As a consequence:
* there is no deduplication among different layer `diff`s
* files are being saved twice in the worst case (once in the OSTree repo and once in the layer `diff`)

Not only that, it's even **breaking** pre-existing hard-links. Just import the Docker `busybox` image on a repository with OSTree configured to see it explode from 1.3M to 423M, because it's deduplicating all the binaries that in Busybox are hard-linked to a single binary.

**Comment by Silvanoc** [comment]
I'm coming closer to the root-cause of this issue...

The "inode index" feature that [appeared first on kernel 4.13](https://github.com/torvalds/linux/commit/02bcd1577400b0b2eab806ccb9f72d6b5ec7bcca) is missing on my kernel: 4.9. Therefore any 'copy up' is breaking the hardlinks from the lower layers.

The question is now if a 'copy up' (that IMO shouldn't be happening) is happening from an OSTree checkout to a layer `diff` directory and due to the absence of the "inode index" feature in my kernel is breaking all the busybox hardlinks.

**Comment by Silvanoc** [comment]
Apparently there's an issue with the option **RequireHardlinks** not being honored by https://github.com/ostreedev/ostree-go in [processOneCheckout](https://github.com/ostreedev/ostree-go/blob/d0388bd827cfac6fa8eec760246eb8375674b2a0/pkg/otbuiltin/checkout.go#L80).
If I add following in there:
```
if opts.RequireHardlinks {
	repoCheckoutAtOptions.overwrite_mode = C.TRUE
}
```
 I get following error message:
```
.../go/src/github.com/containers/storage/vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/checkout.go:109 - Hardlinking 72/45d84b7f2d4620c8a0c50b8d3ff98129fd7718f912b163ace544a252e55bee.file to .dockerenv: Invalid cross-device link
could not checkout from OSTree
```

And I've then observed that `containers-storage` has created a **bind mount** of `${graphroot}/overlay`. What for? I don't know.

Since the OSTree repo is not on the bind mounted directory, OSTree appears to think that they are on different filesystems, although they are on the same...

**Comment by Silvanoc** [comment]
I got it! :tada:

I got bitten by the issue mentioned by @giuseppe in [this commit](https://github.com/containers/storage/commit/f3e7ee3c2ae02e95243dd0772903a48af52c5736) combined with the [issue 29 of ostree-go](https://github.com/ostreedev/ostree-go/issues/29) "hiding" it.

I'll add that information to the documentation that I'm writing within the scope of issue #323. Where I'm BTW still waiting for input from @nalind. [Here](https://github.com/containers/storage/compare/master...Silvanoc:silvano/document-readonly-layers) you can see what I have up-to-now.

I'll leave this issue open until [issue 29 of ostree-go](https://github.com/ostreedev/ostree-go/issues/29) has been fixed.

**Comment by Silvanoc** [comment]
BTW in between I've upgrade to a kernel > 4.13, if not it wouldn't have worked due to the issue mentioned in https://github.com/containers/storage/issues/331#issuecomment-488571557.

**Comment by Silvanoc** [comment]
Is there any reason why the OSTree shouldn't be placed as a subdirectory of *graphroot*?

**Comment by rhatdan** [comment]
@Silvanoc is this still something you want?  Are you still working on it?  @nalind @giuseppe is this something we should pursue?

**Comment by nalind** [comment]
Given #439, I don't think this is applicable any more.

**Comment by Silvanoc** [comment]
> @Silvanoc is this still something you want? Are you still working on it? @nalind @giuseppe is this something we should pursue?

After realizing that OSTree for deduplication is a dead-path within the different involved communities and the issues being faced at it, I'm not anymore interested on it. But thanks for asking!
