### ISSUE TITLE
defaults for runroot in storage.conf

### ISSUE THREAD

**Issue by dustymabe** [containers/storage#359]
Originally mentioned in https://github.com/containers/libpod/issues/3274. All information (system settings, versions) from that issue can be applied here.

On a fresh install of `podman-1.3.1-1.git7210727.fc30.x86_64` if I run rootless podman I end up with a  `~/.config/containers/storage.conf` file with `runroot = "/tmp/1000"` in it. This isn't the most unique directory name. Could we possibly change the default to something like `/var/run/user/1000/containers/storage`?

**Comment by rhatdan** [comment]
I believe it is supposed to default to this, the issue was probably because you did this without setting up xdg_runtime_dir before executing.  IE Login as root and then su to a user or something like that?

If you blow away the file does it work correctly?

**Comment by dustymabe** [comment]
> I believe it is supposed to default to this,

**$this** being `/var/run/user/1000/containers/storage` ?

>  the issue was probably because you did this without setting up xdg_runtime_dir before executing. IE Login as root and then su to a user or something like that?

I started from a vanilla f30 cloud vagrant box and just did `sudo dnf install -y podman && podman run -it --rm registry.fedoraproject.org/fedora:30`

```
Installed:
  podman-2:1.3.1-1.git7210727.fc30.x86_64                         container-selinux-2:2.101-1.gitb0061dc.fc30.noarch         criu-3.12-11.fc30.x86_64                          
  fuse-overlayfs-0.3-10.dev.gita7c8295.fc30.x86_64                podman-manpages-2:1.3.1-1.git7210727.fc30.noarch           slirp4netns-0.3.0-2.git4992082.fc30.x86_64        
  containers-common-1:0.1.36-9.dev.gitd93a581.fc30.x86_64         ostree-libs-2019.2-1.fc30.x86_64                           runc-2:1.0.0-93.dev.gitb9b6cc6.fc30.x86_64        
  containernetworking-plugins-0.7.4-2.fc30.x86_64                 iptables-1.8.0-5.fc30.x86_64                               libbsd-0.9.1-3.fc30.x86_64                        
  libnet-1.1.6-17.fc30.x86_64                                     libnetfilter_conntrack-1.0.7-2.fc30.x86_64                 libnfnetlink-1.0.1-15.fc30.x86_64                 
  libnftnl-1.1.1-6.fc30.x86_64                                    nftables-1:0.9.0-5.fc30.x86_64                             protobuf-c-1.3.1-2.fc30.x86_64                    

Complete!
[vagrant@vanilla-f30 ~]$ ls -a ~/
.  ..  .bash_logout  .bash_profile  .bashrc  .ssh
[vagrant@vanilla-f30 ~]$ 
[vagrant@vanilla-f30 ~]$ ls ~/.config/
ls: cannot access '/home/vagrant/.config/': No such file or directory
[vagrant@vanilla-f30 ~]$
[vagrant@vanilla-f30 ~]$ podman run -it --rm registry.fedoraproject.org/fedora:30
Trying to pull registry.fedoraproject.org/fedora:30...Getting image source signatures
Copying blob 149da9c683f1 done
Copying config edc5d31c98 done
Writing manifest to image destination
Storing signatures
[root@70241606b9a9 /]# exit
exit
[vagrant@vanilla-f30 ~]$ cat ~/.config/containers/storage.conf | grep runroot
  runroot = "/tmp/1000"

```


> 
> If you blow away the file does it work correctly?

no

**Comment by rhatdan** [comment]
Well this is a libpod issue, so we are in the wrong place.

**Comment by dustymabe** [comment]
> Well this is a libpod issue, so we are in the wrong place.

ahh - sorry about that. It's hard to know where to open an issue. Can you **transfer** the issue to libpod ?

**Comment by rhatdan** [comment]
No you were right, it is in containers/storage.  Just opened a PR to fix it. PTAL

**Comment by rhatdan** [comment]
This has been merged.
