### ISSUE TITLE
Carve things up and move storage interfaces to a new model

### ISSUE THREAD

**Issue by vbatts** [containers/storage#37]
Based on recent conversations, let's move away from this codebase that is carried from the Docker graphdriver. Ideally the model like stdlib [`database/sql`](https://golang.org/pkg/database/sql/) would be ideal, where the package imported by other libraries is just a "headers only" style of interface/interaction, and the drivers are imported only by the final `main.main` application.

In doing this, the first/primary use-case will be for overlayfs. The existing implementation of devicemapper will be next, though with a fresh approach using `lvm` directly rather than re-inventing the wheel as the existing devicemapper graphdriver has done.

## Approach

Preliminary review is thinking this model ought to be two interfaces, or exposed functionalities.
One for the notion of an "image storage" (including composed layers, and ephemeral layers (or "containers" which is overused)), and "tree storage" for the file systems themselves.

## `containers/storage.Store` red ink

This is my notes from walking through the places that this behemoth interface is being used or referenced.

n/u - not used; c/i - containers/image; cri-o; c/s - internal use to containers/storage

https://godoc.org/github.com/containers/storage/storage?importers at least the footprint of places this is even used are minimal. Practically no risk of breaking others

n/u:
 - GetRunRoot(): n/u (c/s)
 - GetGraphOptions(): n/u 
 - GetGraphDriver(): n/u 
 - GetLayerStore(): n/u (c/s)
 - GetImageStore(): n/u (c/s)
 - CreateLayer(): n/u (c/s)
 - GetMetadata(): n/u (c/s), (overused name), (this could about _driver_ details) (nothing seems to even read from the `Metadata` fields on these structs)
 - Exists(): n/u (c/s), (overused name)
 - Delete(): ... n/u (overused name)
 - Wipe(): n/u (c/s)
 - Changes(): n/u (c/s)
 - DiffSize(): n/u (c/s)
 - ApplyDiff(): n/u 
 - Layers(): n/u (c/s)
 - ListContainerBigData(): n/u (c/s)
 - GetContainerBigData(): n/u (c/s)
 - GetContainerBigDataSize(): n/u 
 - SetContainerBigData(): n/u (c/s)
 - GetImagesByTopLayer(): n/u 
 - GetContainerByLayer(): n/u 
 - SetContainerDirectoryFile(): n/u 
 - SetContainerRunDirectoryFile(): n/u 
 - GetFromContainerRunDirectory(): n/u 
 - Lookup(): n/u (c/s)
 - Version(): n/u (c/s)

crio only:
 - CreateContainer(): cri-o, c/s, (overused name)
 - DeleteContainer(): crio, c/s 
 - Mount(): crio, (c/s) (overused name)
 - Unmount(): crio, c/s (overused name)
 - Images(): crio, (c/s)
 - Containers(): crio, (c/s)
 - GetNames(): crio
 - GetContainer(): crio
 - GetContainerDirectory(): crio
 - GetFromContainerDirectory(): crio
 - GetContainerRunDirectory(): crio
 - Shutdown(): crio

c/i only:
 - Diff(): c/i 
 - GetGraphRoot(): c/i, c/s 
 - GetGraphDriverName(): c/i 
 - PutLayer(): c/i, c/s 
 - CreateImage(): c/i, c/s 
 - DeleteLayer(): c/i, c/s 
 - DeleteImage(): c/i (overused name)
 - ListImageBigData(): c/i 
 - GetImageBigData(): c/i 
 - GetImageBigDataSize(): c/i 
 - SetImageBigData(): c/i 
 - GetLayer(): c/i 

c/i and crio:
 - SetMetadata(): c/i, cri-o, c/s, (overused name), (where as this is just a Metadata string on the Layer, Container, and Image structs inside c/s... this is not so straight forward)
 - SetNames(): crio, c/i 
 - GetImage(): c/i, crio

**Comment by rhatdan** [comment]
Since it has been two years and know one has chosen to work on this, I think it is safe to close.
