### ISSUE TITLE
Add support for CernVM-FS graph driver

### ISSUE THREAD

**Issue by jwflory** [containers/storage#383]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

[CernVM-FS](https://cvmfs.readthedocs.io/en/stable/cpt-overview.html) (cvmfs) is a read-only, distributed filesystem with use cases specific to research / HPC computing. There is a [CernVM-FS graph driver](https://cvmfs.readthedocs.io/en/stable/cpt-graphdriver.html) for Docker that enables Docker to use cvmfs as a storage back-end.

This is desirable for a number of reasons. For advanced computing environments with parallel file systems (see containers/libpod#3478), there are a number of challenges for user namespaces in these environments. Using cvmfs as a storage back-end for containers works around the existing challenges with parallel filesystems and also allows administrators of these computing environments to store and distribute container images quickly.

A user story:

> Systems Administrator Joe wants to put container image artifacts on a cheaper tier storage than GPFS (containers/libpod#3478) and chose [CernVM-FS](https://cvmfs.readthedocs.io/en/stable/cpt-overview.html). Would a container storage support for cvmfs make sense? Red Hat Quay supports bittorrent. Would cvmfs make sense for Red Hat Quay or should a Quay → cvmfs bridge such as [DUCC](https://cvmfs.readthedocs.io/en/stable/cpt-ducc.html) be used?

**Steps to reproduce the issue:**

1. `podman --storage-driver=cvmfs pull registry.fedoraproject.org/fedora:latest`

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This use case is, as far as I am aware, exclusive to HPC / grid computing administrators for enabling rootless container support in parallel filesystem environments.

**Comment by rhatdan** [comment]
We would need a PR from someone with access to Cern VM-FS.  I am not sure if Fedora or Ubuntu has native support for this.

**Comment by rhatdan** [comment]
@jwflory Is this still something you want to pursue?

**Comment by jwflory** [comment]
@rhatdan Unfortunately it isn't something I'm able to work on right now, sorry!

**Comment by rhatdan** [comment]
@nalind is this something we could handle?

**Comment by nalind** [comment]
I'd have to do more research into it to be certain.

**Comment by SEJeff** [comment]
If it helps, we've got an ok from cvmfs upstream to package it for Fedora and maybe get it into EPEL. I won't be able to work on that for a month or more likely two but did plan on doing that. It is mostly just some c code and libcurl

**Comment by rhatdan** [comment]
Sounds cool.  If anyone else wants to jump on this in the mean time, it would be appreciated.

**Comment by siscia** [comment]
Here from cvmfs team.

I am quite interested in making this happen and our friends in https://github.com/containers/storage/issues/498 seems to be interested as well.

Now the laboratory is close, but second week of January I will definitely take a closer look into this.

In the meantime, happy holidays everybody!

**Comment by rhatdan** [comment]
@jwflory @siscia Is there any chance of this moving forward?

**Comment by siscia** [comment]
I am actually on vacation!

I am setting a reminder for next week as I come back to work.

**Comment by siscia** [comment]
I am now having a quick look at the interface of the layers, that I am guessing is this one (https://github.com/containers/storage/blob/4176c81c99e02a0aac66c3caf60a749773d793f8/drivers/driver.go#L68-L156) 

It does not seems an impossible work to do, I still have some open questions, but with enough work maybe we can make this happens.

Said so, we should understand who is interested in it and how much resource can be poured into it.

Maybe it would be better to focus our efforts on the use of additional storage that allow to mount layers from cvmfs, without the need of a custom driver. Our GSoC to ehance DUCC to support podman is in reasonably good shape.

Related work is done by our friend here: https://github.com/containers/storage/pull/644

And if we find a way to coordinate it would be great.

@jwflory feel free to reach me directly so that we can discuss better your needs.

**Comment by jwflory** [comment]
Hi, I worked on this issue at a previous employer and no longer work with the CernVM-FS stack or in an H.P.C. environment. Other points of contact for follow-up might be @SEJeff, @LandonTClipp, or @lpezzaglia.

**Comment by rhatdan** [comment]
Since there has been no work on this for a while, I am going to close for lack of interest.
