### ISSUE TITLE
make storage options driver-specific

### ISSUE THREAD

**Issue by vrothberg** [containers/storage#423]
Currently the storage-options are shared among drivers while some do not support all of them. We have seen a couple of user issues caused by that for various reasons; a distribution may specify some defaults but the user chooses a different file system (e.g., btrfs) which will then break.

Background discussion: https://github.com/containers/buildah/issues/1825#issuecomment-526140018

**Comment by rhatdan** [comment]
https://github.com/containers/buildah/issues/1859

**Comment by rhatdan** [comment]
Patch has been merged.
