### ISSUE TITLE
High memory usage during image pulls with cri-o

### ISSUE THREAD

**Issue by rkojedzinszky** [containers/storage#433]
With crio when pulling images, high memory usage is observed. With v1.12.14 memory usage is reasonable during an image pull, but with v1.13.1 it is really high. Please see https://github.com/cri-o/cri-o/issues/2847.

Bisecting shows https://github.com/containers/storage/commit/d85da313ef195ca827e3a17db9824971fbb6ec6e causes this.

**Comment by vrothberg** [comment]
Thanks for tracking down the commit. How are you measuring the memory usage? Is it virtual or actually used memory? We had a similar issue over at Skopeo where Grafana seemed to report the memory usage incorrectly: https://github.com/containers/skopeo/issues/714

**Comment by rkojedzinszky** [comment]
Hi, actually, just using gnu time binary. It reports maximum memory usage over process lifetime. Also, if I am quick enough, I can even see this using `top`. Basically, I've found that `tr.RawAccounting = true` causes this, as it is already documented that it might have performance/memory impact.
https://github.com/vbatts/tar-split/blob/master/archive/tar/reader.go#L30

**Comment by rkojedzinszky** [comment]
So, forgot to answer, that is RSS memory, not just virtual.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/storage/pull/435 to fix the issue. Thanks a lot for tracking down the issue, @rkojedzinszky.
