### ISSUE TITLE
OCI image-layout for image store dir

### ISSUE THREAD

**Issue by chrisdostert** [containers/storage#440]
This is more a question than anything else. 

It seems like the image store directory is a custom format.

I'm curious if it's intentional to not use the OCI image-layout for this purpose? It seems like it would be a nice fit.

**Comment by vrothberg** [comment]
The implementation was originally forked from Docker and predates the OCI format but supports storing images in various formats, so we need a certain degree of abstraction - same for the supported drivers. Maybe, the image store would be implemented a bit different today but changing it now would break backwards compatibility.

I guess that @nalind and @rhatdan can give a better background story than me :^)

**Comment by rhatdan** [comment]
Yes the storage layer evolved and predates OCI by many years.  I would only be interested in a Redesign if it gaves us considerable improvements in performance of in size of storage.  Don't see the value in redesign for redesign sake.
