### ISSUE TITLE
opts.go: build fails against docker 19.03

### ISSUE THREAD

**Issue by elboulangero** [containers/storage#450]
```
# github.com/containers/storage/opts
src/github.com/containers/storage/opts/opts.go:299:15: undefined: filters.ToParam
src/github.com/containers/storage/opts/opts.go:309:18: undefined: filters.ParseFlag
```

These functions were removed in Docker `19.03`: https://github.com/moby/moby/commit/c334a87

It seems `ToParam` can be replaced by`ToJSON` as is, but the move from `ParseFlag` to `Args.Add`  seems to be a bit more involving. I'm reaching the limit of my Go knowledge already here...

**Comment by vrothberg** [comment]
Hi @elboulangero, thanks for the report. We'll look into the issue and try to resolve it. Out of curiosity, how did you detect the issue?

**Comment by elboulangero** [comment]
I package Docker for Debian, we have the version `19.03.4` in the experimental suite: https://packages.debian.org/experimental/docker.io

 Now we're at the stage where we spot broken reverse build dependencies (ie. packages that depend on docker, used to build against docker `18.09`, and fail to build against docker `19.03`), and try to fix it. That's the story :)

Thank for the quick answer (although I wonder if it's an automated answer :p )

**Comment by vrothberg** [comment]
Great, thanks for reaching out!

No automated answer but the right caffeine level :) The dependency is small enough to just fork the package. I'll prepare a PR.
