### ISSUE TITLE
please use reasonable line length

### ISSUE THREAD

**Issue by onlyjob** [containers/storage#474]
Some files (e.g. [containers-storage.conf.5.md](https://raw.githubusercontent.com/containers/storage/master/docs/containers-storage.conf.5.md)) have insane line length which makes it needlessly difficult to diff or edit such files in some editors. 

Please consider adopting a style with reasonable restrictions for maximum line length.

This is a best practice and common sense issue.

**Comment by rhatdan** [comment]
Please open a PR to fix the man pages format.

**Comment by onlyjob** [comment]
> Please open a PR to fix the man pages format.

I can do that but would the format be preserved? It was broken recently and that's why we might need a policy or a style guide to avoid such issues in the future.

**Comment by rhatdan** [comment]
Well adding a test would prevent it from being broken again.

**Comment by vrothberg** [comment]
I think we need some markdown formatting tool for such enforcements. Do you know such a tool?

**Comment by rhatdan** [comment]
The difficulty here would be making sure that the man page when rendered in nroff as well as the markdown on a web site still look good.  I was playing with a tool to do this on Emacs, but it was adding extra spaces to make everything line up, and looked like crap.

**Comment by giuseppe** [comment]
the Emacs fill-region command seems to work fine here.

We could script it:

```
$ cat auto-fill.el 
(require 'package)

(add-to-list
 'package-archives
 '("melpa" . "http://melpa.org/packages/")
 t)
(package-initialize)

(unless (package-installed-p 'markdown-mode)
  (package-install 'markdown-mode))

(markdown-mode)
(fill-region (point-min) (point-max) nil t t)
(save-buffer)

$ emacs --batch docs/containers-storage.conf.5.md -l $(pwd)/auto-fill.el
```

(I've not tested the case where the markdown-mode package is missing, as it is already installed on my system)

**Comment by rhatdan** [comment]
I think this is fixed, reopen if this is incorrect.
