### ISSUE TITLE
[unit test] system.Lsetxattr failed

### ISSUE THREAD

**Issue by zhuguoliang** [containers/storage#517]
How to repproduce?
` cd pkg/archive
go test -run TestOverlayTarUntar`
 
result:

> --- FAIL: TestOverlayTarUntar (0.00s)
    archive_linux_test.go:30:
        	Error Trace:	archive_linux_test.go:30
        	            				archive_linux_test.go:103
        	Error:      	Received unexpected error:
        	            	operation not permitted
        	Test:       	TestOverlayTarUntar
FAIL
exit status 1
FAIL	github.com/containers/storage/pkg/archive	0.002s

**Comment by zhuguoliang** [comment]
Can be done with sudo, thought sudo is not needed with podman, closing now.

**Comment by rhatdan** [comment]
It should not be needed.  What is in the tar file?  It could be a conflict in fuse-overlay.
Potentially a problem with SELinux labels trying to be assigned while in a fuse-overlay file system.
