### ISSUE TITLE
additionalimagestores config option ignored

### ISSUE THREAD

**Issue by gartnera** [containers/storage#544]
`additionalimagestores` is parsed into `GraphDriverOptions` here: https://github.com/containers/storage/blob/67c7e82f5c10e86a8ce29add27c0450ad76c6bfb/store.go#L3331-L3333

However, `GraphDriverOptions` is overwritten on the here:
https://github.com/containers/storage/blob/67c7e82f5c10e86a8ce29add27c0450ad76c6bfb/store.go#L3378

If I comment out the above line, my `additionalimagestores` is parsed into `overlay.imagestore` and passed to the overlay driver correctly. Reference: 

https://github.com/containers/storage/blob/67c7e82f5c10e86a8ce29add27c0450ad76c6bfb/drivers/overlay/overlay.go#L289

Looks like this is the PR that broke it: https://github.com/containers/storage/pull/432

**Comment by rhatdan** [comment]
@gartnera Interested in opening a PR?

**Comment by rhatdan** [comment]
Is the graphdrivername being set?
