### ISSUE TITLE
panic when trying to update last-writer without write-lock

### ISSUE THREAD

**Issue by haircommander** [containers/storage#575]
we somehow encountered this in CRI-O:
```
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: time="2020-03-26 16:46:25.447845722Z" level=info msg="About to del CNI network lo (type=loopback)"
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: panic: attempted to update last-writer in lockfile without the write lock
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: goroutine 139197 [running]:
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: panic(0x1b3d9c0, 0x2166ba0)
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: 	/usr/local/go/src/runtime/panic.go:1060 +0x420 fp=0xc000825d50 sp=0xc000825ca8 pc=0x43c860
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: github.com/containers/storage/pkg/lockfile.(*lockfile).Touch(0xc000350eb0, 0xc000fc6720, 0x0)
Mar 26 16:46:25 ip-172-18-1-199.ec2.internal crio[26020]: 	/go/src/github.com/cri-o/cri-o/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:193 +0x235 fp=0xc000825dd0 sp=0xc000825d50 pc=0x7a2ae5
```

[ref](https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3482/test_pull_request_crio_e2e_crun_fedora/2409/artifacts/journals/crio.service)

What's going on here, why is this a panic, and is there anything callers of c/storage can do to prevent this?

**Comment by mrunalp** [comment]
@nalind @TomSweeneyRedHat @rhatdan ptal.

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
> What's going on here, why is this a panic, and is there anything callers of c/storage can do to prevent this?

We _must_ panic when detecting violations of the lock protocol to prevent data corruption. `(*lockfile).Touch()` has either been called without owning the lock OR at the time of being a reader. But we need to own the lock as a writer to update its metadata.

@haircommander, is it happening in master?

I really don't have any cycles left at the moment to look into it unless the Jedi council asks me to prioritize over podman v2.

**Comment by umohnani8** [comment]
@vrothberg yes it is happening in master. This will be an issue when we bump up cri-o to 1.18 for 4.5 as this blows up on crio-wipe when crio is restarted. I also hit this when testing out changes I made to crio by switching out the binaries on a cluster.

**Comment by vrothberg** [comment]
@umohnani8, do you have a reproducer? That would be ideal.
