### ISSUE TITLE
zfs driver fails at chown

### ISSUE THREAD

**Issue by rottaran** [containers/storage#602]
Dear developers,
I get following error message when building from docker files, for example, https://github.com/diegogslomp/samba-ad-dc

```
Error: error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[yum update -y] Flags:[] Attrs:map[] Message:RUN yum update -y Original:RUN yum update -y}: error copying layers and metadata for container "40baf6bf2a7f60d455279f160223354decae52d17e4a966cb680506bf9968ec6": Error initializing source containers-storage:centos-working-container: error extracting layer "9a6dda6e1eb9e097fbe3374c9aa20abab3365585845121bd28f30b8af5ef17a8": error modifying zfs mountpoint (/var/lib/containers/storage/zfs/graph/aff9833d464191900b4a3b6e68aad912f930de639b411124e433aeb3757001cd) directory ownership: chown /var/lib/containers/storage/zfs/graph/aff9833d464191900b4a3b6e68aad912f930de639b411124e433aeb3757001cd: read-only file system
```

The command that fails is in https://github.com/containers/storage/blob/847e58e7c9560a8e3ab105a3927da902b32bdd59/drivers/zfs/zfs.go#L411

Same issue on on CentOS 7 as well as CentOS 8

```
$ yum info containers-common.x86_64 
Name       : containers-common
Architektur : x86_64
Epoche             :2
Version    : 0.2.0
Ausgabe    : 2.1.el7
Größe : 44 k
Quelle      : installed
Aus Quelle  : devel_kubic_libcontainers_stable
```

my /etc/containers/storage.conf looks like this:
```
[storage]
driver = "zfs"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]

[storage.options.zfs]
fsname="testpool/containers"
mountopt="nodev"
```

I have not set up rootless containers and subuid/subgid, just running as root.

**Comment by rhatdan** [comment]
This looks like the image is being mounted read/only for some reason.

**Comment by rottaran** [comment]
My guess was, that the chown fails when applied to the mount point. However, I don't know enough about how that works. Might it be related to the changes made in the overlay driver in pull request #404 or #358 ?

**Comment by sa687** [comment]
I think btrfs had the same issue which was discussed at https://github.com/containers/libpod/issues/3773

rhatdan said that was [caused by the "ro" option](https://github.com/containers/libpod/issues/3773#issuecomment-519959987) that was added to fsdiff.go. https://github.com/containers/storage/pull/416 was a fix for btrfs, but it looks like no fix was applied for the zfs driver

**Comment by rottaran** [comment]
Thank you for the pointer. Thus, I should drop "ro" from `options.Options` after this line: https://github.com/containers/storage/blob/master/drivers/zfs/zfs.go#L387 ? 

But then everything is mounted writable. I guess that the chown at the end of `Get()` just shouldn't be applied on read-only mounts. Or at least, fail silently. I could not find a similar chown in the overlay driver's `Get()` code.

**Comment by rhatdan** [comment]
That sounds quite possible.  Please open a PR to fix this and we will get it in.

**Comment by asteven** [comment]
I have the same problem as the OP.
I'm trying to fix it, but would appreciate some hints how to build this lib and then podman from source to actually test it.

**Comment by asteven** [comment]
Never mind, figured out how to build.

`podman build` now works for me with the patch from d345632, where before it failed with the error mentioned by the OP.
