### ISSUE TITLE
Add support and tests for limiting disk usage

### ISSUE THREAD

**Issue by nalind** [containers/storage#61]
The overlay driver doesn't have any notion of limiting disk usage, and the devicemapper driver lets us specify the size of the thin pool device, but not much more.  We should explore implementing a more uniform (and uniformly enforceable) way of managing disk usage, and of putting upper bounds on how much space a container can use.

CCing @mrunalp, who I'm hoping has better insight as to what consumers of a runtime like cri-o actually expect usage limits to mean.

**Comment by rhatdan** [comment]
@rhvgoyal Has thoughts about this I believe.  I think we can do somethings with xfs to limit size on overlayfs

**Comment by rhvgoyal** [comment]
docker has a pending patch to limit size of container using xfs project quota with overlay graph driver. Its worth looking at it.

https://github.com/moby/moby/pull/32977

**Comment by rhatdan** [comment]
Overlay now supports quota.

**Comment by Silvanoc** [comment]
> Overlay now supports quota.

@rhatdan Internally? Without using XFS? How? I could find a way to get it done.

**Comment by rhatdan** [comment]
Only with XFS.

**Comment by rhatdan** [comment]
We have quota built into storage now for both overlay and devicemapper.  CLosing.
