### ISSUE TITLE
Make the fuse-overlay binary path configurable at build time

### ISSUE THREAD

**Issue by nlewo** [containers/storage#622]
It would be nice to be able to configure at build time the path of the `fuse-overlay` binary. If not configured, it could still rely on the `PATH` as currently implemented (https://github.com/containers/storage/blob/master/utils.go#L151).

This would avoid to add a wrapper Skopeo in the Nix package. See PR  https://github.com/NixOS/nixpkgs/pull/87659.

**Comment by rhatdan** [comment]
Why not just specify the path in storage.conf under the overlay section?

**Comment by nlewo** [comment]
Because I didn't know the existence of this file;) Thanks @rhatdan !
