### ISSUE TITLE
bug in the layerStore.Mount() ?

### ISSUE THREAD

**Issue by abel-von** [containers/storage#624]
when the `layerStore.Mount()` is call more than once for a same id, the layer can not be removed and will be residue on the host.

when I investigate into this, I found that the logic to avoid dulicated mount in the layerStore.Mount has some problem, first let's see what to do in the `layerStore.Mount()` when the `layer.MountCount` bigger than 0: 

```
 	if layer.MountCount > 0 {
		mounted, err := mount.Mounted(layer.MountPoint)
		if err != nil {
			return "", err
		}
		// If the container is not mounted then we have a condition
		// where the kernel umounted the mount point. This means
		// that the mount count never got decremented.
		if mounted {
			layer.MountCount++
			return layer.MountPoint, r.saveMounts()
		}
	}
```
it will call `mount.Mounted()` with `layer.MountPoint` as the parameter, but when you really call this, the returned `mounted` is false even the layer is actually mounted.
because the `layer.MountPoint` is a form like `/var/lib/docker/devicemapper/mnt/xxxxxxxxx/rootfs`, the actual mount point is `/var/lib/docker/devicemapper/mnt/xxxxxxxxx`, with no `rootfs` appened.

the `mount.Mounted()` will check the `/proc/self/mountinfo` to see if `/var/lib/docker/devicemapper/mnt/xxxxxxxxx/rootfs` is mounted, of course, it won't find it.

**Comment by abel-von** [comment]
I think this PR has some problem,  even if we find the rootfs is not mounted, and call the driver.Get(), driver has another counter and the duplicated call to Get() with the same id will do nothing.
https://github.com/containers/storage/pull/496

```

func (d *Driver) Get(id string, options graphdriver.MountOpts) (string, error) {
	d.locker.Lock(id)
	defer d.locker.Unlock(id)
	mp := path.Join(d.home, "mnt", id)
	rootFs := path.Join(mp, "rootfs")
	if count := d.ctr.Increment(mp); count > 1 {
		return rootFs, nil
	}
```

**Comment by abel-von** [comment]
at least it is what devicemapper driver do

**Comment by rhatdan** [comment]
Are you interested in opening a PR to fix the problem?

**Comment by rhatdan** [comment]
With the overlay driver the layer.MountPoint is something like
/home/dwalsh/.local/share/containers/storage/overlay/9c3847385c56fda91796ec164a50066d744706ae0a8dbd6e22ef7745b2edf67d/merged
Which is the mount point, so this works correctly.
In devicemapper, why is the MountPoint set to the rootfs directory, if it's parent is the actual mount point?
@rhvgoyal Any ideas?

**Comment by rhatdan** [comment]
@abel-von Still interested in this, or can I close?
