### ISSUE TITLE
[proposal] Add cleanup method for graphdrivers to unmount home mount

### ISSUE THREAD

**Issue by kolyshkin** [containers/storage#696]
Many (or all?) graph drivers create a bind mount of their home directories in order to set mount propagation to private. This mount is never unmounted, i.e. there is no "Cleanup" function or something that a higher level tool like CRI-O could use during shutdown to clean things up. As this mount is internal to the graph driver, the undoing of it should also be internal.

I propose to add `Cleanup()` or `Shutdown()` function can be added. This should facilitate cleaner runtime shutdown.

(Opening the issue first to gather some feedback first)

**Comment by rhatdan** [comment]
I believe this is umounted when you shutdown the store.

store.Shutdown()

**Comment by rhatdan** [comment]
I just fixed something like this in Buildah 2d57fc6c3f31e3cac4b029da8c95d5d0c1a2fbfb

**Comment by rhatdan** [comment]
I think I answered this reopen if I am mistaken.
