### ISSUE TITLE
TestDefaultStoreOpts fails in debian package build

### ISSUE THREAD

**Issue by siretart** [containers/storage#712]
When trying to update the debian package to version 1.23.4, I'm getting this error while running the tests:

```
=== RUN   TestDefaultStoreOpts
    utils_test.go:268: assertion failed: /<<PKGBUILDDIR>>/debian/tmp-home/run/containers (storageOpts.RunRoot string) != 1000/containers/storage (expectedPath string)
--- FAIL: TestDefaultStoreOpts (0.00s)
```

The location stems from here:
https://github.com/containers/storage/blob/01ce1c303af6b7fadd08b5733bf4f83ddcda575b/utils_test.go#L268

In order to see the old and new path, I've applied this patch locally:

```
diff --git a/utils_test.go b/utils_test.go
index 4c9595fe2..57497e3b8 100644
--- a/utils_test.go
+++ b/utils_test.go
@@ -265,7 +265,7 @@ func TestDefaultStoreOpts(t *testing.T) {
 	expectedPath := filepath.Join(os.Getenv("NAME"), "1000", "containers/storage")
 
 	assert.NilError(t, err)
-	assert.Assert(t, storageOpts.RunRoot == expectedPath)
-	assert.Assert(t, storageOpts.GraphRoot == expectedPath)
-	assert.Assert(t, storageOpts.RootlessStoragePath == expectedPath)
+	assert.Equal(t, storageOpts.RunRoot, expectedPath)
+	assert.Equal(t, storageOpts.GraphRoot, expectedPath)
+	assert.Equal(t, storageOpts.RootlessStoragePath, expectedPath)
 }
```

The Debian build is running outside of a container as [fakeroot](https://wiki.debian.org/FakeRoot). Also, because the builds start with `$HOME` set to a non-existent location (and the tests expect `$HOME` to be writable), I've setup non-standard environment variables during the build (cf. https://salsa.debian.org/go-team/packages/golang-github-containers-storage/-/blob/fc8528c94ed4bc0996d0546ef3950a39c3c7ba6b/debian/rules#L7-23)

I'll probably exclude this test from the packaging for now, but that's quite unfortunate. I believe there is a bad assumption in the test that might have been overlooked in https://github.com/containers/storage/pull/683

**Comment by rhatdan** [comment]
Interested in filing a PR to make the test work the way you want?

**Comment by siretart** [comment]
I'm not sure how to fix the issue, and the patch above seems kind of trivial, but I sure can put that patch in a PR if you think it'd be useful

**Comment by rhatdan** [comment]
Open up a PR to apply your patch.

**Comment by vrothberg** [comment]
> Open up a PR to apply your patch.

Note that the patch doesn't fix it but it shows the mismatching items.

**Comment by siretart** [comment]
Fair enough, filed as #715 715

@vrothberg is right, that patch doesn't fix anything. I think the test should fail whenever `XDG_RUNTIME_DIR` is set in the environment to some path that points to an empty directory (which is what the debian package does during the build)

**Comment by rhatdan** [comment]
Interested in opening a PR to do this?

**Comment by rhatdan** [comment]
Since this Patch was merged, I am closing.

**Comment by siretart** [comment]
@rhatdan that patch only makes the error message clearer, but doesn't resolve anything. I am not familiar enough with the code to fix it myself, sorry :-(
