### ISSUE TITLE
[RFE] Warning when graphroot is on an NFS volume

### ISSUE THREAD

**Issue by jcpunk** [containers/storage#734]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Can rootless podman emit a warning if 'backingFs=nfs`

**Steps to reproduce the issue:**

1. Build system with /home/ on NFS

2. Setup user namespaces

3. run rootless podman

4. Get error

**Describe the results you received:**

Rootless podman does not run with graphroot on an NFS volume.  No clear hint that it is an Unsupported Filesystem is provided.

**Describe the results you expected:**

Since NFS cannot support rootless podman, could podman emit a notice of some type so that users are aware they need to alter their storage config.

Eventually I found : https://www.redhat.com/sysadmin/rootless-podman-nfs

**Additional information you deem important (e.g. issue happens only occasionally):**

Since this is a known incompatibility, emitting a pointer to the possible issue at some log level would be very helpful.

**Output of `podman version`:**

```
podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

**Comment by giuseppe** [comment]
when NFS is detected, fuse-overlayfs is automatically configured to store the metadata on xattrs so that the NFS storage is usable.

Fixed with 175c8db45205b51cf875f982c0bfcfdf3d3dec4f
