### ISSUE TITLE
ignore_chown_errors + additionalimagestores = failure

### ISSUE THREAD

**Issue by plopresti** [containers/storage#735]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Setting both ignore_chown_errors and additionalimagestores in ~/.config/containers/storage.conf does not work if the additional image store is owned by a different user. (Specifically, ignore_chown_errors appears not to take effect.)

**Steps to reproduce the issue:**

1. As one user (userA), create an image store under /some/directory. "chmod -R a+rX /some/directory". (Per https://www.redhat.com/sysadmin/image-stores-podman)

2. As another user (userB), set ignore_chown_errors = true and additionalimagestores = [ "/some/directory"] in ~/.config/containers/storage.conf.

3. podman run -it some_image bash # Where some_image is under /some/directory, but not in userB's own image store

**Describe the results you received:**

```
Error: error creating container storage: error creating read-write layer with ID "9bde3b894d4c0e7364f99e3ed4791345c032392edf475327adef547bc5889b5e": there might not be enough IDs available in the namespace (requested 65534:65534 for /scratch/ricao/containers/storage/overlay/9bde3b894d4c0e7364f99e3ed4791345c032392edf475327adef547bc5889b5e): chown /scratch/ricao/containers/storage/overlay/9bde3b894d4c0e7364f99e3ed4791345c032392edf475327adef547bc5889b5e: invalid argument
```

**Describe the results you expected:**

Shell prompt.

**Additional information you deem important (e.g. issue happens only occasionally):**

Note this is the same error as if "ignore_chown_errors" is not set. Running with an image from userB's own image store works fine. Also, putting /some/directory in userA's additionalimagestores also works fine. It is only when the additionalimage store is owned by a different user that "ignore_chown_errors" seems to be disabled / ignored.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15
Built:        Sun Sep 27 19:07:17 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: efe288263ebb1bab4673d2cfbe1a352f3c7d27c1-dirty'
  cpus: 64
  distribution:
    distribution: '"scientific"'
    version: "7.8"
  eventLogger: journald
  hostname: vex4
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 422
      size: 1
    uidmap:
    - container_id: 0
      host_id: 22101
      size: 1
  kernel: 3.10.0-1127.19.1.el7.x86_64
  linkmode: dynamic
  memFree: 58210488320
  memTotal: 404159303680
  ociRuntime:
    name: runc
    package: runc-1.0.0-103.dev.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 70f396b2cfa8fb0c6c12bd46020af4744b9eff5b
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/22101/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.el7.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 17162039296
  swapTotal: 17179865088
  uptime: 868h 43m 4.24s (Approximately 36.17 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/ricao/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "true"
    overlay.imagestore: /scratch/patl/shared
    overlay.mount_program:
      Executable: /bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.el7.x86_64
      Version: |-
        fusermount3 version: 3.6.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  graphRoot: /scratch/ricao/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/22101/containers
  volumePath: /scratch/ricao/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601258837
  BuiltTime: Sun Sep 27 19:07:17 2020
  GitCommit: ""
  GoVersion: go1.15
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-4.el7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical CentOS 7 system.

**Comment by plopresti** [comment]
That next error comes from `createIfNotExist`, here:

https://github.com/opencontainers/runc/blob/dc9208a3303feef5b3839f4323d9beb36df0a9dd/libcontainer/rootfs_linux.go#L886

...when called by `prepareBindMount`, here:

https://github.com/opencontainers/runc/blob/dc9208a3303feef5b3839f4323d9beb36df0a9dd/libcontainer/rootfs_linux.go#L205

As far as I can tell, `prepareBindMount` is trying to create the mount points for various bind mounts, but these are failing because the containing directories (e.g. .../merged/etc) are owned by nfsnobody. (Presumably the additionalimagestore owner when outside the container).

And that is as far as I got today.

**Comment by plopresti** [comment]
@rhatdan

With a bit of hacking, I actually have this working.

First, as mentioned above, I deleted this stanza from overlay.go in the podman libstorage code:
 
https://github.com/containers/storage/blob/v1.23.5/drivers/overlay/overlay.go#L574-L581

Next, I had to make some changes to fuse-overlay. I replaced the entire body of `find_mapping`, here:

https://github.com/containers/fuse-overlayfs/blob/323b01f17478aad992dc69e9195d83bb490008d6/main.c#L647-L666

with this:

```
static unsigned int
find_mapping (unsigned int id, struct ovl_mapping *mapping, bool direct, bool uid)
{
  if (direct)
      return 0;
  return id;
}
```

This is the function that maps UIDs/GIDs inside the overlay mount. This change maps everything in the lower layers to zero inbound to the overlay, while doing no mapping outbound from the overlay. Although I am not 100% sure, I believe this is what we want for `ignore_chown_errors`.

Finally, I set `mount_program` in my storage.conf with a shell script that contains:

```
#!/bin/sh
exec env LD_PRELOAD=/path/to/ignore-chown-errors.so /bin/fuse-overlayfs "$@"
```

Where `ignore-chown-errors.so` is the following gadget:

[ignore-chown-errors.c.gz](https://github.com/containers/storage/files/5337325/ignore-chown-errors.c.gz)

All it does is intercept calls to chown, fchown, lchown, etc., makes the underlying system call, and then returns zero to pretend it succeeded.

After all of that, ignore_chown_errors + additionalimagestores is working for me. Obviously this is a huge hack and probably breaks lots of other use cases, but hopefully it can help someone fix this bug properly.

The right fix, I think, is for fuse-overlayfs to be made "ignore_chown_errors aware", probably via a mount option.

**Comment by rhatdan** [comment]
@giuseppe WDYT?

**Comment by giuseppe** [comment]
I am fine if we extend fuse-overlayfs with a `squash-to-root` kind of option.  We could then use it from `mountopt` in the `storage.conf` file without having to modify other tools.

**Comment by giuseppe** [comment]
@plopresti would you like to open a PR for fuse-overlayfs?

**Comment by plopresti** [comment]
@giuseppe Sure. But note that making this work requires more than just `squash-to-root`. Even with that code change, I still get a variety of `chown/fchown/fchownat/etc` errors. Instead of tracking all of those down, I just threw together an LD_PRELOAD hack to ignore all of the failures.

Is it OK if `squash-to-root` also ignores such errors? I will track down exactly which ones are failing. (I can even make the code changes if you like.)

**Comment by giuseppe** [comment]
> @giuseppe Sure. But note that making this work requires more than just `squash-to-root`. Even with that code change, I still get a variety of `chown/fchown/fchownat/etc` errors. Instead of tracking all of those down, I just threw together an LD_PRELOAD hack to ignore all of the failures.

yes, I think the squash-to-root should prevent these errors too.  Do you know how they are happening?  Isn't any UID/GID being mapped back to 0?

**Comment by plopresti** [comment]
> yes, I think the squash-to-root should prevent these errors too. Do you know how they are happening? Isn't any UID/GID being mapped back to 0?

I do not know exactly, yet.

In `ignore_chown_errors` mode, root inside the container is mapped to the single unprivileged user outside the container, and there are no other mappings (I believe). So any attempt to "chown" anything tends to fail. Thus far I have been figuring this out by staring at strace output. I will see if I can get it running under gdb and track down the exact failures. Thanks!

**Comment by plopresti** [comment]
Moving this part of the discussion to https://github.com/containers/fuse-overlayfs/issues/241

**Comment by giuseppe** [comment]
closing as it was fixed in fuse-overlayfs.  Not sure there is anything else we can do from containers/storage
