### ISSUE TITLE
     when pulling an image by tag we need to always store the digested reference along with the tag (same as docker does)

### ISSUE THREAD

**Issue by rhatdan** [containers/storage#76]
@nalind @mtrmac here's the situation:
    when pulling an image by tag we need to always store the digested reference along with the tag (same as docker does)
    we don't have a RepoDigests for ImageStatus and we just fill RepoTags with status.Names which just contains tagged references for that image
    (guess what) we need RepoDigests slice
    digests must not be stored and shown as the ID of an image (see reproducer 1). The image ID in docker is the digest of its config blob which should be unique due to content addressability!
    if you pull an image by digest corresponding to a tag different than latest image list reports that it has a :latest tag whether that's not true at all (see reproducer 2)
    image ID should be the config blob digest!

--

reproducer 1 (digest shown as image ID, the image ID should be the config digest blob!):

$ crioctl image pull nginx@sha256:4aacdcf186934dcb02f642579314075910f1855590fd3039d8fa4c9f96e48315
$ crioctl image list
ID: 4aacdcf186934dcb02f642579314075910f1855590fd3039d8fa4c9f96e48315
Tag: docker.io/library/nginx:latest

--

reproducer 2 (wrong tag applied to a digested image, there should not be any tag for this image unless someone has previously pulled the same image by tag!):

# this is the digest for redis:alpine but redis:latest is shown below, incorrectly
# notice how the same issue as reproducer 1 is shown below (ID != digest)
$ crioctl image pull redis@sha256:03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b
$ crioctl image list
ID: 03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b
Tag: docker.io/library/redis:latest

https://github.com/kubernetes-incubator/cri-o/issues/531

**Comment by rhatdan** [comment]
Copied from kubernetes-incubator/cri-o#531

**Comment by mtrmac** [comment]
To be a pest, is there a _specific reason_ why is this necessary? Not that using the docker-like behavior is _bad_, it’s just not the obviously only possible way to organize things. Is the motivation only to exactly what Docker does, whatever it is, or is there a specific use case which needs to work, or a design issue which is best solved by doing things this way?

FWIW a separate `RepoDigests` field may not be necessary, at least when using containers/image to store images, the original manifest is stored as “big data" named `manifest`; so we can recompute the digest on-demand (_if_ the “image” objects are not deduplicated by `config.json`, then multiple images with different manifests with exactly the same `config.json` would only store one manifest / manifest digest).

**Comment by rhatdan** [comment]
@runcom WDYT

**Comment by runcom** [comment]
@mtrmac @rhatdan we need this to reach feature parity with Docker when working with CRI-O and Kubernetes. I'm fine if we have this as a knob that cri-o uses, we just need it to match dockers behavior.

**Comment by rhatdan** [comment]
@nalind Did we ever do this?  Is this something still worth doing?

**Comment by mtrmac** [comment]
Now that we actually store all the manifests, and a `repo@sha256:`_digest_ reference to the local image won’t break, yes, we probably should record this data.

**Comment by rhatdan** [comment]
@nalind Time to work on this one?

**Comment by nalind** [comment]
I think the two reproducers work as expected at this point (since https://github.com/cri-o/cri-o/pull/1116 or so).  Please reopen if there's something still missing there.
