### ISSUE TITLE
archive.Changes() does not  correctly show diffs between two unrelated layers

### ISSUE THREAD

**Issue by 14rcole** [containers/storage#82]
If archive.Changes() is called and the two layers provided to it are not directly related (e.g. a layer and it's parent or grandparent), Changes() will provide the diff of the layer from its parent as opposed to the diff of the two layers.

This could be problematic in cases such as comparing two images with the same parent in order to determine their differences.

**Comment by rhatdan** [comment]
@nalind Do you think this is still an issue?

**Comment by rhatdan** [comment]
After 1.5 years and no action, I am closing this issue.
