### ISSUE TITLE
"Does not support overlay" intermittent error

### ISSUE THREAD

**Issue by aweiteka** [containers/storage#84]
When running cri-o integration tests on F25 I sometimes get an error that overlay is not enabled in the kernel:

```
"'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
```

I haven't reproduced this when overlay is manually enabled before running. [More details here](https://paste.fedoraproject.org/paste/T3bF-chLII7ujSsk9VeopA).

Speaking to @rhatdan he suspects the 'supportsoverlay' function is racing through too quickly: https://github.com/containers/storage/blob/master/drivers/overlay/overlay.go#L219

**Comment by rhatdan** [comment]
@nalind @aweiteka and I just looked at this and I think it might be a race condition in the test to see if overlay is supported.

I believe below that the /proc/filesystem can be read before the modprobe overlay completes?
```
func supportsOverlay() error {
	// We can try to modprobe overlay first before looking at
	// proc/filesystems for when overlay is supported
	exec.Command("modprobe", "overlay").Run()

	f, err := os.Open("/proc/filesystems")
	if err != nil {
		return err
	}
	defer f.Close()
```

**Comment by nalind** [comment]
`Run()` is documented to wait for the child process to exit before it returns (compare to using `Start()` and `Wait()`), so I don't think that there's a race condition in here.

**Comment by rhatdan** [comment]
Well I will close https://github.com/containers/storage/pull/123 and see if this happens to anyone again.
