### ISSUE TITLE
The mount attribute "userxattr" is added also for older kernels

### ISSUE THREAD

**Issue by afbjorklund** [containers/storage#863]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman doesn't work, without a custom storage.conf to avoid automatic mount attributes

```
[storage]
  driver = "overlay"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

Since https://github.com/containers/storage/commit/6cb8896a97f8f82d6ed86be1051577aceb1fd580

**Steps to reproduce the issue:**

1. podman run -it fedora

2.

3.

**Describe the results you received:**

```
ERRO[0000] error unmounting /home/anders/.local/share/containers/storage/overlay/bd4e743f04a1cc32a0ea773106aab080e41cfeaa8420fca55f3da652258699c9/merged: invalid argument 
Error: error mounting storage for container 0db16dd90da5d0b7d2ed9c4f2f8173dd4d8b54b17493191712acd4ff8950b3a0: error creating overlay mount to /home/anders/.local/share/containers/storage/overlay/bd4e743f04a1cc32a0ea773106aab080e41cfeaa8420fca55f3da652258699c9/merged, mount_data=",lowerdir=/home/anders/.local/share/containers/storage/overlay/l/5JPBLHPVKX7YIMTJTCDYSGHYX3,upperdir=/home/anders/.local/share/containers/storage/overlay/bd4e743f04a1cc32a0ea773106aab080e41cfeaa8420fca55f3da652258699c9/diff,workdir=/home/anders/.local/share/containers/storage/overlay/bd4e743f04a1cc32a0ea773106aab080e41cfeaa8420fca55f3da652258699c9/work,userxattr": invalid argument
```

**Describe the results you expected:**

```
#
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Linux 5.4

**Output of `podman version`:**

```
podman version 3.1.0-dev
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by afbjorklund** [comment]
> I think it could be [cf4c912](https://github.com/containers/storage/commit/cf4c9126f07091a20103918d5efb02e1f59c7fb6)

Indeed it was, `supported: false`

**Comment by rhatdan** [comment]
So can we close this issue?

**Comment by giuseppe** [comment]
yes let's close if it works also on Ubuntu

**Comment by afbjorklund** [comment]
It might have been an "upgrade problem" or somesuch, but giving the mount_program explicitly would work in that case...

The main message is that rootless mounts doesn't work with those kernels, and it seems like new installs now know this.
