### ISSUE TITLE
Make fails on golang 1.16.3

### ISSUE THREAD

**Issue by smijolovic** [containers/storage#869]
$ make containers-storage

rm -f images_ffjson.go
tests/tools/build/ffjson images.go
images_ffjson.go
rm -f layers_ffjson.go
tests/tools/build/ffjson layers.go
layers_ffjson.go
rm -f containers_ffjson.go
tests/tools/build/ffjson containers.go
containers_ffjson.go
rm -f pkg/archive/archive_ffjson.go
tests/tools/build/ffjson pkg/archive/archive.go
pkg/archive/archive_ffjson.go
GO111MODULE=on go build -mod=vendor -compiler gc -tags " libdm_no_deferred_remove "  ./cmd/containers-storage
`#` github.com/containers/storage/pkg/archive
**pkg/archive/archive_ffjson.go:13:2: imported and not used: "io/fs"
pkg/archive/archive_ffjson.go:1652:17: fs.FileMode undefined (type *v1.FFLexer has no field or method FileMode)**
make[2]: *** [Makefile:54: containers-storage] Error 2

Works fine with go 1.15.11

**Comment by rhatdan** [comment]
It is working on golang 1.16.4 for me.
