### ISSUE TITLE
Confused base images between recording and name-setting

### ISSUE THREAD

**Issue by cevich** [containers/storage#915]
Encountered, while testing `podman build ... --arch=$ARCH` in parallel for several flavors of `$ARCH` with the same DockerFile:

(example from the s390x build)
```
STEP 1: FROM registry.fedoraproject.org/fedora:latest
  Getting image source signatures
  Copying blob
sha256:2e3e38c2d45f6e160e30c78275c3e36e5175ff6c03a385af1426b629d57b807e
  Copying config
sha256:d8ff5720673b9ef6c24da183c7d4303796903b7bf569b76230a186660772c8e1
  Writing manifest to image destination
  Storing signatures
  Error: error creating build container: error loading image manifest for "containers-storage:[overlay@/home/runner/.local/share/containers/storage+/tmp/podman-run-1001/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]registry.fedoraproject.org/fedora:latest":
error locating item named "manifest" for image with ID
"3567369c671193f96f057f76e3e136ecbd3fdc7065019cc3dd6ed5a96894f128": file
does not exist
```

@nalin said

>It looks like two pulls are getting confused when using the image with
the name of the base image.  The image ID for a v2s2 or OCI image is the
same as the digest of the config blob, but the image ID in the error
("3567369c671193f96f057f76e3e136ecbd3fdc7065019cc3dd6ed5a96894f128") is
not the same as the digest of the config blob that's being pulled
("d8ff5720673b9ef6c24da183c7d4303796903b7bf569b76230a186660772c8e1").
>
>It looks like it's failing to load a manifest from the second image
because you hit the window between when the image record is created and
the name is set on it, and when the manifest is saved to the the image
record.  It's a small tweak to change the order of those things so that
the name is set on the image only after every part of it has been saved,
which would avoid the error we get while attempting to read the
manifest.
>
>However, the problem where one build might find, and try to use as its
base image, an image that was just-now pulled for a different arch,
isn't something we can remove without making much, much bigger changes.

**Comment by cevich** [comment]
***Note***: In case anybody else encounters this, a functional workaround is:

Run the parallel builds each with a different `--root` and `--runroot` locations.  Combining the manifest at the end by exporting each image first, e.g. into `docker-archive` files.

**Comment by nalind** [comment]
There are two things mentioned above.  The first was a containers/image thing (https://github.com/containers/image/pull/1232).

**Comment by cevich** [comment]
What the heck!  I double-checked your e-mail and a it said `containers/storage` but now it says `containers/image`!  I can't believe my eyes!  Clearly somebody has hacked into the server and altered the text of the e-mail!  It's the ***only*** logical explanation!
