### ISSUE TITLE
Static binary keeps reexecing 

### ISSUE THREAD

**Issue by ricardomaraschini** [containers/storage#959]
I have the following reproducer that attempts to load a docker image from disk (tar file) into local storage:

```go
package main

import (
        "context"
        "log"
        "time"

        imgcopy "github.com/containers/image/v5/copy"
        "github.com/containers/image/v5/signature"
        "github.com/containers/image/v5/transports/alltransports"
        "github.com/containers/storage/pkg/reexec"
        "github.com/containers/storage/pkg/unshare"
)

func main() {
        if reexec.Init() {
                panic("reexec returned true")
        }
        unshare.MaybeReexecUsingUserNamespace(true)

        ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
        defer cancel()

        pol, err := signature.NewPolicyContext(
                &signature.Policy{
                        Default: signature.PolicyRequirements{
                                signature.NewPRInsecureAcceptAnything(),
                        },
                },
        )
        if err != nil {
                log.Fatal(err)
        }

        fromref, err := alltransports.ParseImageName("docker-archive:x.tar")
        if err != nil {
                log.Fatal(err)
        }

        toref, err := alltransports.ParseImageName("containers-storage:myregistry.io/repo/img:latest")
        if err != nil {
                log.Fatal(err)
        }

        if _, err := imgcopy.Image(
                ctx,
                pol,
                toref,
                fromref,
                &imgcopy.Options{},
        ); err != nil {
                log.Fatal(err)
        }
}
```

This works fine if I compile like so:

```
go build -o /tmp/bin main.go
```

If I attempt to build it as a static binary the program never finishes. This is how I am compiling:

```
CGO_ENABLED=0 go build -tags containers_image_openpgp -ldflags="-extldflags -static" -mod vendor -o /tmp/bin main.go
```

I have noticed that the binary keeps been rexec()ed. The environment is the following and I am running the binary as a regular user:

```
go version go1.16 linux/amd64
Linux kakkerlakken 5.11.22-100.fc32.x86_64 #1 SMP Wed May 19 18:58:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

The only difference I could see is that on the non static binary, after reexec, [this](https://github.com/containers/storage/blob/main/pkg/unshare/unshare_linux.go#L384)  `os.Geteuid()` function returns 0. On the static binary it returns 1000 and that causes a new reexec.

**Comment by nalind** [comment]
Replace the `panic("reexec returned true")` with `return true`.  That's the recommended usage for `reexec.Init()`.

**Comment by ricardomaraschini** [comment]
> Replace the `panic("reexec returned true")` with `return true`. That's the recommended usage for `reexec.Init()`.

Do you mean a simple `return` (as main does not return anything)? I've put a `return` there but the problem persist.

**Comment by ricardomaraschini** [comment]
These are the processes I can see when I run the static binary:

```
$ ps -ef |grep /tmp/bin |grep -v grep
rmarasch 2989041 2883118  0 20:25 pts/15   00:00:00 /tmp/bin
rmarasch 2989051 2989041  2 20:25 pts/15   00:00:00 /tmp/bin-in-a-user-namespace
rmarasch 2989062 2989051  0 20:25 pts/15   00:00:00 /tmp/bin-in-a-user-namespace-in-a-user-namespace                                                                                                                 rmarasch 2989072 2989062  1 20:25 pts/15   00:00:00 /tmp/bin-in-a-user-namespace-in-a-user-namespace-in-a-user-namespace
... and this keeps going on...
```

The initial process stops [here](https://github.com/containers/storage/blob/main/pkg/unshare/unshare_linux.go#L156), it never reads the pid.

**Comment by ricardomaraschini** [comment]
Not sure if relevant but posting here as it might help. This is the environment variables I can see when the process is execv'd with the "normal" binary (filtered only by variables starting with `_`):

```
_=/tmp/bin
_CONTAINERS_USERNS_CONFIGURED=done
_CONTAINERS_ROOTLESS_UID=1000
_CONTAINERS_ROOTLESS_GID=1000
```

This is the same output, after execv'd the static binary:

```
_=/tmp/bin
_CONTAINERS_USERNS_CONFIGURED=done
_Containers-unshare=268566528
_CONTAINERS_ROOTLESS_UID=1000
_CONTAINERS_ROOTLESS_GID=1000
_Containers-pid-pipe=3
_Containers-continue-pipe=4
```

**Comment by ricardomaraschini** [comment]
I can confirm that [this](https://github.com/containers/storage/blob/main/pkg/unshare/unshare.c#L299) function is not called from the static version of the binary.

**Comment by ricardomaraschini** [comment]
With CGO disable this won't work. Closing it.
