### ISSUE TITLE
Make the store work for unprivileged user

### ISSUE THREAD

**Issue by mgoltzsche** [containers/storage#96]
Unfortunately this library cannot be used by unprivileged users since mounting is not permitted.

As a workaround for use cases where there is no root access a simple driver should be added that works without actually mounting anything (accepting poor performance).

**Comment by rhatdan** [comment]
@nalind Does vfs support this mode?

**Comment by nalind** [comment]
Not currently - the remounting of the runroot at startup happens regardless of which driver we're using.  If we dropped that, and with the right UID/GID mapping (so that when we explode layers onto disk, we don't fail to fix up permissions), I think it would.

**Comment by mgoltzsche** [comment]
That would be great and with vfs this could be the very basic solution for this issue.

Ideally I had a mtree-based driver in mind that would work like https://github.com/openSUSE/umoci but I see now that this only makes sense for unprivileged users after the remounting outside the driver is dropped.

**Comment by rhatdan** [comment]
Adding support for ostree might be interesting also.

**Comment by cyphar** [comment]
@mgoltzsche Yeah, `umoci` does this already (as well as having built-in support for rootless containers :wink:). In addition to removing the remounting code, and verifying that the permissions are set up properly, you'd also need to handle a lot of `CAP_DAC_OVERRIDE` edge-cases. I made a library (`github.com/openSUSE/umoci/pkg/unpriv`) that transparently emulates `CAP_DAC_OVERRIDE` in userspace for unprivileged users.

**Comment by mgoltzsche** [comment]
After digging a little deeper into the storage `Store`/`Driver` interfaces I realized it is tricky - if not impossible - to be implemented efficiently using mtree. For my use case (image build) a simpler interface with a `Commit` method is more suitable to take advantage of mtree.

@rhatdan ostree might be interesting indeed.

@cyphar thanks for the update. I'll definitely have another look at umoci again also regarding CAP_DAC_OVERRIDE.

**Comment by cyphar** [comment]
@mgoltzsche I have been talking to @hallyn about potentially having something like `umoci revert` which will allow you to do some more complex operations efficiently (it would generate an index from the layers to be able to efficiently look up the blob data).

**Comment by giuseppe** [comment]
I am trying to run "vfs" in an user namespace, and I see this error when I try to commit the image:

```
error committing container "fedora-working-container-2" to "giuseppe/lighttpd": error copying layer and metadata: error committing new image "containers-storage:[vfs@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]docker.io/giuseppe/lighttpd:latest": error determining uncompressed digest for blob "sha256:20b069c8f6656b620092a273cb5c4e5ecce943e32a19c67d1c447bcb6499d141"
```

Does it depend from https://github.com/containers/image/pull/305 ?

**Comment by nalind** [comment]
@giuseppe That message was introduced in https://github.com/containers/image/pull/305, so the tool that produced it already includes a later version of the image library.

**Comment by giuseppe** [comment]
@nalind yes, I meant if it was introduced by https://github.com/containers/image/pull/305

To track better this problem, I've opened a new issue here:

https://github.com/projectatomic/buildah/issues/502

**Comment by rhatdan** [comment]
This looks like it is fixed,  Closing reopen if this is still an issue.
