### ISSUE TITLE
Support quota for overlay2

### ISSUE THREAD

**Issue by mrunalp** [containers/storage#97]
We need to support quota support to limit containers in overlay2 with xfs similar to docker.

https://github.com/moby/moby/blob/8af4db6f002ac907b6ef8610b237879dfcaa5b7a/daemon/graphdriver/overlay2/overlay.go#L202

@nalind @rhatdan

**Comment by mrunalp** [comment]
cc: @runcom

**Comment by runcom** [comment]
:+1:

**Comment by nalind** [comment]
Closing by #98.
